### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by nk932714** [Tzahi12345/YoutubeDL-Material#1]
blank page after deployment on heroku

**Comment by Tzahi12345** [comment]
Could you look at the console and see what it outputs when the page loads?

It's usually right click -> inspect -> console.

**Comment by Tzahi12345** [comment]
I know this is an old issue, but because it is related, I wanted to let you know that I was able to get a Heroku deployment up and running!

You can click the *Deploy to Heroku* link at the top of the [README](https://github.com/Tzahi12345/YoutubeDL-Material#youtubedl-material), or this button below:

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/Tzahi12345/YoutubeDL-Material)

Anyways, that's all! Closing issue :)

**Comment by nk932714** [comment]
Thank you so much @Tzahi12345
