### ISSUE TITLE
[BUG] npm ERR

### ISSUE THREAD

**Issue by ukdanmc** [Tzahi12345/YoutubeDL-Material#1034]
Hi,

I am running docker on a Synology, this has been working for a while now.
Now when the container start's then restarts I get this NPM permission error. Any suggestion?

Your cache folder contains root-owned files, due to a bug in
youtubedl-ytdl_material-1  | npm ERR! previous versions of npm which has since been addressed.
youtubedl-ytdl_material-1  | npm ERR! 
youtubedl-ytdl_material-1  | npm ERR! To permanently fix this problem, please run:
youtubedl-ytdl_material-1  | npm ERR!   sudo chown -R 1038:100 "/.npm".

**Environment**
- YoutubeDL-Material version 4.3
- Docker tag: nightly

**Comment by rlively** [comment]
@martadinata666 
I am encountering this same issue (only started after I added UID and GID to the compose file).
The latest compose file for docker is using tzahi12345/youtubedl-material:latest which was built in May of 2023.
The commit with the fix was pushed in December of 2023 (https://github.com/Tzahi12345/YoutubeDL-Material/pull/1035/commits/509e9961078a7d82c2fc69f0377904f6e9e827f1). How do I pull the docker image containing this fix?
On the releases page (https://github.com/Tzahi12345/YoutubeDL-Material/releases) I don't see any after May, 2023.
