### ISSUE TITLE
Multiuser Issue & Archive Issue (using docker nightly)

### ISSUE THREAD

**Issue by airbillion** [Tzahi12345/YoutubeDL-Material#109]
1. When I enable multiuser mode and try to download a video or audio it does not complete.  A "user" folder is created, but nothing downloads to it and the download fails.

Log:
2020-05-30T01:26:10.331Z INFO: Binary successfully updated: 2020.05.08 -> 2020.05.29
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'users/admin/audio/archives/archive_audio.txt'

at Object.openSync (fs.js:440:3)
at /app/app.js:1540:37
at new Promise (<anonymous>)
at generateArgs (/app/app.js:1462:12)
at /app/app.js:1346:38
at new Promise (<anonymous>)
at downloadFileByURL_normal (/app/app.js:1323:12)
at /app/app.js:1894:28
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at next (/app/node_modules/express/lib/router/route.js:137:13)
at complete (/app/node_modules/passport/lib/middleware/authenticate.js:268:13)
at /app/node_modules/passport/lib/middleware/authenticate.js:275:15
at pass (/app/node_modules/passport/lib/authenticator.js:431:14)
at Authenticator.transformAuthInfo (/app/node_modules/passport/lib/authenticator.js:453:5)
at /app/node_modules/passport/lib/middleware/authenticate.js:272:22
at IncomingMessage.req.login.req.logIn (/app/node_modules/passport/lib/http/request.js:55:13)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2. I have the archive checkbox selected in the settings and I successfully download a youtube video/audio and check the archive file created, but no entries show up.  This happens with and without multiiser mode enabled.

**Comment by Tzahi12345** [comment]
Just wanted to drop in and let you know I solved the first bug you noticed, but the second bug actually also applies to multi user mode. Basically, the --download-archive argument is getting completely ignored.

Still trying to figure out why, I'll let you know when I get both fixes pushed to the nightlies!

**Comment by Tzahi12345** [comment]
Good news and bad news: I tracked down the underlying bug, but it reveals a larger fundamental problem with our main dependency (read more [here](https://github.com/Tzahi12345/YoutubeDL-Material/issues/111)). Basically, there are two download methods of downloading: a "safe" method that does a simple download, and the "unsafe" approach which gives you things like download progress.

What I learned is that the unsafe method does not support archiving. This was a problem because there was no way to force the backend to use the safe method manually (so if you don't care about video progress, but do care about archives, you can't just use the safe approach). So, I included that option! (see [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/dcc7fbd81cee6a0f7a1bc35e1e402d2b9f30425e)). If you get the newest nightly and go into the `Downloader` tab in the settings, you will see the new override at the bottom of the tab.

So until we get a new library for video downloads, you're going to have to rely on the safe download override setting to use the archive feature. Let me know if you run into any issues enabling/using the override.

Thanks for the bug report! They're always appreciated :)

**Comment by airbillion** [comment]
Great!

Thank you for fixing the bugs and giving the option for the downloads. 

I'll let you know if I have any issues. 

Thanks!
