### ISSUE TITLE
Update Readme: Audit Contributor Setup Steps

### ISSUE THREAD

**Issue by web-connect** [Tzahi12345/YoutubeDL-Material#132]
I had to install a package (Fixed with #128), and I had to install angular globally. Make sure its pretty clear on how to get it setup so people can contribute easier.

**Comment by Tzahi12345** [comment]
Yup, this is 100% an area that needs improvement. Clear docs for how to contribute, general guidelines, etc. Also, I'd like to include in there graphics, or an explanation dedicated to the code structure (since that can be confusing, even if we do the suggested refactor).

**Comment by Tzahi12345** [comment]
Readme is updated to include a link to the new [contributing](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Contributing) guidelines. It's not 100% finished yet, but it has the most essential information there. What's mostly missing is an overview of the code. I'm resistant to do this for the backend since a change is planned there anyways.

Anyways, this should clear up confusion on how to get setup with developing for this project. Let me know if any of it is confusing!
