### ISSUE TITLE
Setting delays for subscriptions

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#134]
I just watched a video from CNN on YouTube and wondered why it was 480p instead of the what these days is "the new SD" default: 720p.

And then it dawned on me: check the upload time. Well sure enough, 27 min old video.

When our subscriptions function fetches new uploads even with fixed maximums for refresh rate and resolution you will run into the problem that often videos take a while to process to be available in full resolution and all formats.

I think it'd be reasonable to allow these two things:

a) allow the user to delay a download once a subscription is triggered.

b) allow to download a smaller format/fps and "upgrade" it later automatically and/or manually.  (whatever the user prefers)

I think options like waiting until a specific codec is available can cause problems, like when YT stops supplying a certain codec we'll run into broken subs, causing massive maintenance. So limiting to having res and fps as factors seems reasonable at least for now.

Greetings from 480p land (yuck XD)

**Comment by Tzahi12345** [comment]
I remember thinking about this edge case in the past, not surprised to see this come up!

I think I prefer option b here. What I think I'll do is flag a subscription video if its upload date is close to its download date (let's say within 1 hour of uploading, ofc this can be customizable). We can call that the `fresh_upload` flag.

Once that delay elapses and the subscription check initiates, the new, better format can be downloaded no problem. Of course once this finishes, the `fresh_upload` flag gets set back to false.

The reason why I think option A isn't possible here is because we don't know what videos will be downloaded from the subscription prior to the actual download (we have a similar problem in regular downloads as well). So I think the flag option here is the best approach.

This won't be possible to implement immediately (we need the next iteration of subscriptions which will drop in 4.1), but that's nearly done and is the biggest feature update in 4.1. As always, thanks for the suggestion! Seems like an easy fix, let's see how long it'll take to implement ;)

**Comment by Tzahi12345** [comment]
This is done! Before you try pulling the latest nightly, this has not been merged yet but you can see the details in the [relevant PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/290). You'll be able to use this in v4.2 which should come sometime in the next couple weeks. Here's a preview of the setting and its tooltip below:

![image](https://user-images.githubusercontent.com/707413/102686264-6affcd80-41b4-11eb-9028-97c85dcc0cb9.png)

I'll go ahead and close this issue, thanks for the suggestions as always!
