### ISSUE TITLE
Remove pin functionality

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#147]
Since we already have a working authentication system with user and password credentials I don't see why it is still possible to have a pin secured options.

I would even consider it a security risk because by default, when no pin has been set (but the admin password has been set) the app asks the user to set a pin. I don't even see a way to disable pin login.

That's why I suggest to remove it.

**Comment by Tzahi12345** [comment]
It's a relic from before multi-user mode was added. I kept it in as an option for those who want to protect their settings, but don't want to enable multi-user mode.

It's redundant and should probably be removed. Also:

>I would even consider it a security risk because by default, when no pin has been set (but the admin password has been set) the app asks the user to set a pin.

sounds like a bug. Fixing that doesn't seem worth the effort when it's unlikely the pin feature will be used now that multi-user mode has been implemented. I'll queue it up for removal for v4.2 (since v4.1 is pretty much feature complete)

**Comment by Tzahi12345** [comment]
Done! Check out the [latest commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/dd80c51f16e990b6c7c811e2c2090866039e0ab5).

**Comment by NotErikUden** [comment]
Is there a way to have a public user? Like, I want anyone to be able to use the site without having to sign up, I just don't want everyone to be able to change settings that could potentially kill the site.

**Comment by UnlimitedCookies** [comment]
Currently there is no such feature. You could open an issue requesting a guest user, where all videos are deleted after a certain amount of time.
