### ISSUE TITLE
Docker ENv questions

### ISSUE THREAD

**Issue by gerroon** [Tzahi12345/YoutubeDL-Material#15]
Hi

I am looking at the docker-compose file and I am a bit confused. I am wondering if I could get some answers to q below

- Why do we have 2 ports, one ytdl and one for docker ports?

- I do not want to serve it over web. How do I disable LE certs?

- How do I set external download folders? Where are they saved as of now?

- Which option is neded for saving downloads on the server, and disabling clientside download.

thanks

**Comment by Tzahi12345** [comment]
> Why do we have 2 ports, one ytdl and one for docker ports?

This may be something I can simplify later in Docker, but the app itself requires you to set a port. Because you're in Docker, this can be anything (as long as you specify it after the `:` in `ports:` as well). The container also outputs on a port you can specify as well, but not everyone uses Docker, and those who do also need the ability to set an output port (which in their case in ytdl_port).

I know this is a little confusing. It's definitely something I need to work on.

> I do not want to serve it over web. How do I disable LE certs?

Encryption is disabled by default. In the docker-compose, this corresponds to the `ytdl_using_encryption` environment variable (should be set to `'false'` in your case).

>How do I set external download folders? Where are they saved as of now?

The audio and video folders are set by the `ytdl_audio_folder_path` and `ytdl_video_folder_path` in docker-compose.yml. These are relative to the root path of the program (in a container this is the `/app` folder).

A natural question is how to get your files, which are saved in the container, *out* of the container. I believe you would need to use Docker [volumes](https://docs.docker.com/storage/volumes/) to get set up. This ability may be something I want to provide by default later.

>Which option is neded for saving downloads on the server, and disabling clientside download.

By default, the downloads are all stored on the server and the client will stream content from the server once the download finishes. Of course you can always download it client-side still by clicking the blue save button when streaming.

To make it download client-side by default (sounds like you do not want this), set `ytdl_download_only_mode` to `'true'`. The files will still get stored on the server as well.

**Comment by gerroon** [comment]
Awesome help, thanks.

**Comment by gerroon** [comment]
Hi

One issue I seem to have is that I do not want to watch any video or download anything on the client. I want videos directly go to the server. 

I enabled the download only mode since I do not want streaming, but this time it tries to download to the client when it is done. Is it possible to disable any form of downloading or streaming on the client after I enter a video url?

**Comment by Tzahi12345** [comment]
>Is it possible to disable any form of downloading or streaming on the client after I enter a video url?

If you click the 'Multi-download mode' checkbox you will have this functionality, the video gets downloaded and the client won't be redirected. This mode is intended for downloading multiple videos at a time, but it works just fine for one as well.

Make sure that `ytdl_allow_multi_download_mode` is set to `'true'` (it is by default).

**Comment by gerroon** [comment]
Ok thanks I will try it.
