### ISSUE TITLE
Home screen symmetry improvement :P

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#161]
Currently, the individual items on the home screen are indented differently (especially the URL bar) making the interface look not too uniform.
See the picture below.

![image](https://user-images.githubusercontent.com/49200216/87156953-c9e42100-c2bd-11ea-8bff-9fc5717bcf21.png)

Best regards!

**Comment by Tzahi12345** [comment]
The biggest resistance I have to making this change is that we're already planning on redesigning the home page (see #106), so this won't be an issue in the next update. If you'd like to make it look good anyways for the rest of 4.1, go ahead!

Otherwise I'll close this issue once the redesign is done. If you notice anything else that looks weirdly asymmetrical or if any spacing seems weird, feel free to post it in this thread. I'll make sure to address it for the next update. Thanks!

**Comment by UnlimitedCookies** [comment]
Yep, a complete interface overhaul deprecates this issue, didn't see that before (my bad).

**Comment by Tzahi12345** [comment]
This is resolved! This is what it looks like now

![image](https://user-images.githubusercontent.com/707413/100554189-00b4d680-3261-11eb-99d6-584537c1cf0b.png)
