### ISSUE TITLE
Can't subscribe to twitch videos

### ISSUE THREAD

**Issue by suckerfish** [Tzahi12345/YoutubeDL-Material#162]
Maybe this is something I'm doing wrong, but I cannot subscribe to a Twitch channel. Maybe my syntax is wrong, but I used to do this using the youtube-dl CLI. This is the URL syntax that always worked for me with the CLI:

https://www.twitch.tv/(username)/videos/all

But when I set up a sub with that, it doesn't grab the videos.

**Comment by Tzahi12345** [comment]
Subscriptions are actually meant to be YouTube only, but to be honest, I can't see why it failed with Twitch. This would be a cool feature to add (non-YT support) so I'll keep this issue open.

Did you get any errors in the container/logs? Might be helpful in figuring out what went wrong.

**Comment by suckerfish** [comment]
Yes, dozens of these entries. "ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

I did just update to the latest nightly and restarted container and dozens of these entries appear about 30 seconds after the container restart. I already removed the twitch subscription leaving only a single YT subscription active. And that seems to be working just fine, so not sure if these log entries have anything to do with the Twitch problem or are a separate issue.

**Comment by Tzahi12345** [comment]
Can you try subscribing using this format instead?

`https://www.twitch.tv/{username}/videos?filter=all&sort=time`

**Comment by suckerfish** [comment]
When I do this, the logs state as such:

`2020-07-15T23:48:22.718Z ERROR: ERROR: 80568358 is offline
2020-07-15T23:48:22.718Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.`

**Comment by GlassedSilver** [comment]
I'd be very very interested in this as well.

Especially if we could record channels' streams without depending on VODs. Although we should grab them if they are available and not already stream-recorded content.

But stream-capturing as well would be very handy, for two reasons:
copyrighted music would not get muted and secondly we don't rely on the VOD actually becoming available.

This would of course require good handling of a stream maybe becoming unavailable for a certain time, for example when your internet connection goes down for a moment.

Just thinking aloud here. VODs would be the first stop though I think.

**Comment by davidnewhall** [comment]
I concur. Adding a feature like this will draw more users in that want to automatically archive their streams.

**Comment by Tzahi12345** [comment]
This is actually working on my end, when I use the `https://www.twitch.tv/{username}/videos/all` URL format. Can you try it again and see if it works? You probably want to deselect "download all uploads" when subscribing to avoid waiting until *all* of the channel's videos are downloaded.

![image](https://user-images.githubusercontent.com/707413/100554737-c2211b00-3264-11eb-8647-91abc45d2d20.png)

**Comment by Tzahi12345** [comment]
This issue seems stale to me, it should be possible with the URL above. I'll close it, but if you're still experiencing this problem I'll open it back up again.

**Comment by GlassedSilver** [comment]
Yeah this is solved. As far as my request concerning live video capture from Twitch is concerned, I definitely think I ought to flesh this out in a separate feature request for trackability and because it's probably more than "add a line of code" quick. One would have to solve the issue of at least two things:

a) DO display in the UI when a live channel is being recorded - for several reasons, one of them being you wouldn't shut down the instance for maintanance or updates if you knew it was recording something in the background that's live and hence possibly lost if the channel doesn't offer VODs or gets muted in parts in the VOD, etc... definitely do offer to do both: keep live recording and VOD
b) Probably needs some integration with Twitch to receive alerts for when a subbed channel goes live. This would avoid checking for a live stream too late if just doing one-off checks each time per channel subscription interval.
