### ISSUE TITLE
Access to settings before login with Multi-user mode enabled

### ISSUE THREAD

**Issue by EmTeeAge** [Tzahi12345/YoutubeDL-Material#179]
Hi! I recently enabled Multi-user mode to try it out and was a bit surprised that I was still able to access the Setting from the login screen, even before logging in. This allowed anyone who entered the login screen to have full access to the Setting and change anything.

![image](https://user-images.githubusercontent.com/67438185/88590516-604c6c80-d04a-11ea-9dfe-1c51b2820885.png)

I'm not sure what goals exactly you had in mind for Multi-user mode, but I would assume the main points were to give multiple people the ability to have their own playlists and Audio/Video sections on the main screen and also to make sure those lower privileged accounts couldn't edit the server settings. However, even though I am not able to edit the Setting as a non-admin user, I can change them before logging in.

Is this a correct behavior or the Settings aren't supposed to be accessible from the login screen before logging in? :)

Also, the Setting seemed to behave slightly off - they worked but when I opened the Setting from the login screen and clicked on Users, there weren't any showing up. I also wasn't able to add any new users, because the button was disabled. 
(Settings on the login screen)
![image](https://user-images.githubusercontent.com/67438185/88592680-eae29b00-d04d-11ea-8275-0b4f20f10b9f.png)
What I was able to do however, was to Allow user registration. So I tried to enable that, add a new user and log in - that worked fine (even though I wasn't supposed to be allowed to enable the this setting in the first place). This new user added through the registration showed up normally in the regular Settings, but I still wasn't able to see any users in the Settings that are accessible from the login screen.
(Settings after login)
![image](https://user-images.githubusercontent.com/67438185/88593361-f6829180-d04e-11ea-8471-a45dce2ff1b5.png)

The only other piece of information that I have are these requests from Firefox's developer tab. This happens when I click on the Setting on the login screen:
![image](https://user-images.githubusercontent.com/67438185/88592156-11540680-d04d-11ea-90a9-a6bed7d242db.png)
getUsers
![image](https://user-images.githubusercontent.com/67438185/88592230-347eb600-d04d-11ea-99bb-dc0efcdd8242.png)
getRoles
![image](https://user-images.githubusercontent.com/67438185/88592261-41030e80-d04d-11ea-90cc-316a5e134b0c.png)

Compared to the requests made when clicking the Setting after login:
![image](https://user-images.githubusercontent.com/67438185/88593597-5416de00-d04f-11ea-909e-eed84331ba40.png)
getUsers
![image](https://user-images.githubusercontent.com/67438185/88593630-5ed17300-d04f-11ea-92fe-9d650311d79b.png)
getRoles
![image](https://user-images.githubusercontent.com/67438185/88593655-685adb00-d04f-11ea-941e-3f3e6d715320.png)

It's not really a huge deal since I'm using YoutubeDL Material only on a home server with my family.

And btw, this issue persists across browsers - tested on Firefox, ungoogled Chromium and old Edge.

Thanks :)

**Comment by Tzahi12345** [comment]
It's definitely a bug! I've gone ahead and fixed it, check out the [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/cd18bce50998989fb28bacd41216e4dd439795de).

Thanks for all the screenshots! Always helpful in the debugging process to get a bunch of info. You actually found another bug in there: even if non-users could access the settings, they shouldn't have been able to set the config. You can see the commit for that bug fix [here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/3ebc903ce9a4acc2d351a190372c008abad2eae6). This doesn't solve that problem for non-admin users, but since they can't access it anyways I don't see it as a high priority item.

Anyways, you can get the fixes immediately by using the `nightly` tag on Docker. Thanks for all the help!! Lmk if you run into any other issues.

**Comment by kylethedeveloper** [comment]
This seems like it hasn't been fixed. I have the same issue. I have enabled multi-user option, created some users, but I can still access "Settings" without login and change every possible option in there. Please inform me about this. @Tzahi12345

**Comment by Tzahi12345** [comment]
@kylethedeveloper Because there hasn't been a release since early July ([explanation here](https://github.com/Tzahi12345/YoutubeDL-Material/discussions/248)), you need to use the `nightly` tag on Docker to get this fix. Once you update the issue should be fixed -- let me know if you still have the issue after updating!

**Comment by kylethedeveloper** [comment]
That made much more sense. Thanks for the quick response. It fixed the issue. Then, I suggest you to edit [README Docker Section](https://github.com/Tzahi12345/YoutubeDL-Material#setup).

Have a nice day.

**Comment by Tzahi12345** [comment]
@kylethedeveloper glad I could help, just updated the instructions on the README to include that note. Thanks for the suggestion!
