### ISSUE TITLE
(some) Playlist improvement ideas

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#214]
Hey! So... after the readding of content to my db has worked nicely I am now looking at the UX again and working with playlists more. Damn I love this application, it is beyond helpful and by Lord did the legacy code help with the rebuilding the db... Mighty glad we still have that code from the transition of a db-less ytdl-m.

Couple thoughts:

1. The playlist editor should show the entries for the playlist in reverse order (latest top) so you can quickly check which recent additions have made it to the list.
2. The button to add a video should be added to the top of the window, so you don't have to scroll all the way down to add more content, this will be especially important the more content is added to lists.
3. Speaking of scrolling... Playlists should be a tab in the sidebar next to Subscriptions and Downloads I think. Maybe between Home and Subscriptions.
4. Speaking of that add button... A button to add a video to a playlist should be in the three dot menu for the video thumbnail and from the player imho... Would really help with those quick adds! :)
5. Maybe also display which playlists a video belongs to. (if it's more than 2 just show the 2, decided by which ones are the busiest playlists. :) (those are usually more of a "category" kind of importance level, e.g. you may have one big list for your music) - this does not replace the tag idea, mind you!
6. And last but not least: it would be handy to assign (multiple) playlists to a video at download time. Ideally also allowing to create a new playlist from there.

The UI for the last idea could be put into the "Advanced" slide out panel in a second tab in there maybe. Not sure yet, just giving an intermediary idea here.

Cheers!

**Comment by Tzahi12345** [comment]
Sorry for the late reply, glad you like the new system!

>The playlist editor should show the entries for the playlist in reverse order (latest top) so you can quickly check which recent additions have made it to the list.

Sounds possible, but I'd like to simply allow users to view it in reverse order. Reason I say this is because in Google Play Music/Spotify it's in normal order, but I can add a simple button to toggle this (and even remember the preferred choice)

>The button to add a video should be added to the top of the window, so you don't have to scroll all the way down to add more content, this will be especially important the more content is added to lists.

Good idea! it's kinda unwieldy to have it all the way down with a bunch of videos

>Speaking of scrolling... Playlists should be a tab in the sidebar next to Subscriptions and Downloads I think. Maybe between Home and Subscriptions.

Ahh.. interesting... probably a better place for it, do you think we shouldn't even show it in the home page (have it reserved for videos) and just show them in the sidebar?

>Speaking of that add button... A button to add a video to a playlist should be in the three dot menu for the video thumbnail and from the player imho... Would really help with those quick adds! :)

Another great idea! Simple yet sweet.

>Maybe also display which playlists a video belongs to. (if it's more than 2 just show the 2, decided by which ones are the busiest playlists. :) (those are usually more of a "category" kind of importance level, e.g. you may have one big list for your music) - this does not replace the tag idea, mind you!

There's UI space considerations for this, but you're right in that we can address the "category" and "playlists" labels at the same time. Here's what I think: in the info dialog, all the info will be seen. But, for the file cards, only the large cards have the space to show the video's categories or playlists. Once categories gets finished (it's about 80-90% done) I'll make sure that the playlist(s) are also mentioned.

>And last but not least: it would be handy to assign (multiple) playlists to a video at download time. Ideally also allowing to create a new playlist from there.

Hm, having a hard time understanding how you would create a new playlist from that. To make sure I understand you correctly, you want to have a dialog where you select one or more videos, and then select the playlists where you want those videos to be added?

Would the new playlist just be the videos you're currently adding to the other playlists?

>The UI for the last idea could be put into the "Advanced" slide out panel in a second tab in there maybe. Not sure yet, just giving an intermediary idea here.

I've been thinking for a while that the "slide out panel" design is a bit raw. In general these expansion panels don't feel so "material design-y" even though that component was made by Google themselves. A separate tab could work for sure!

All of these seem pretty easy to implement, I think the last 3 or so need more exploration. But these simple quality-of-life additions will for sure be beneficial, and since they seem to be low-effort tasks, I'll push it in with v4.2!
