### ISSUE TITLE
Add subscription videos to playlists?

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#223]
Hmm, I just tried to add some subscription videos to playlists, but that seems not to be working.

Is this a bug or am I running into a design limitation here?

Cheers and thanks for any and all help! :)

**Comment by Tzahi12345** [comment]
This is a design limitation, so it's a bit difficult to do but it isn't impossible. The short version of why this isn't trivial is because playlist files are stored as strings, referring to their file names. These file names work just fine for one-off downloads, but for subscriptions it requires storing the subscription id

I just tried to do a quick implementation and got through 2/3 of the major roadblocks, but not all. The roadblock I didn't get through is just how complicated the player component has become. It supports video/audio files, playlists (of both types), subscriptions, and sharing. AND it does all of that for both multi-user mode and single-user mode. And because this was all built incrementally as features got implemented, it's kind of exceeded it's original purpose.

So while a quick fix isn't possible, it will be once the player component is reworked internally. I also want to give it a UI refresh preferably before the next update which will add play counts (#222) and video descriptions if available.

**Comment by GlassedSilver** [comment]
Oh wow, alright. Doesn‘t the DB have IDs for any type of content that‘s shared? If there isn’t due to different implementations it could be worth considering to add this with a transitional period so working content would be facilitated in future for I guess many different kinds of ideas where differentiation between how and which type of content is more of an obstacle?

Anyhow, thanks a lot for the info on the details as well, very interesting for sure and cannot wait for that sweet sweet new player :D

**Comment by Tzahi12345** [comment]
>Doesn‘t the DB have IDs for any type of content that‘s shared?

Files, subscriptions, playlists, and even users have a unique ID. But the unique ID isn't enough to play content, you also need to know whether it's a regular file, subscription, or a playlist. And lastly (this applies to multi-user mode when a video is shared to a non-user), we want to know the user ID of the *owner* of the video. 

It actually isn't *that* complicated now that I think about it. The architecture of the player component and related backend routes were made at a time when there weren't playlists or subscriptions or multi-user mode or sharing videos/playlists, and so we basically need to recreate that logic so it applies to the current system -- otherwise it's going to be bug ridden. In fact, I caused like 5 bugs just trying to implement subscription videos, and it shouldn't be that hard ideally.

I'll hold off on implementation until I get some other items checked off, namely categories/tags which stalled for the last week or so (not enough time in the day!). But yeah, I'm also excited to see the player redone, it's about time.

**Comment by GlassedSilver** [comment]
If I'm not completely off this would also be useful prerequisite to facilitate the function to automatically sort one-off downloads for a given channel into the subscription folder logic if the channel had been subscribed to later on after the one-off download, right? (and by extension have it displayed in the subscriptions as well)

**Comment by GlassedSilver** [comment]
Hoozah!
