### ISSUE TITLE
Video page is behind password protected "paywall"

### ISSUE THREAD

**Issue by maltokyo** [Tzahi12345/YoutubeDL-Material#224]
Can I somehow give YoutubeDL-Material a user name and password for it to login to a site, and then download the video?

I have a user/pw (paid account) for this site, and would like to take the video offline:

https://www.realvision.com/shows/the-expert-view/videos/has-everything-changed-with-raoul-pal

**Comment by Tzahi12345** [comment]
Unfortunately this site is not [supported by youtube-dl](https://ytdl-org.github.io/youtube-dl/supportedsites.html). You can check out that link to see the supported sites. Those that are supported and require login work with the username/password parameters.

To see how to do this check out the [authentication options](https://github.com/ytdl-org/youtube-dl#authentication-options) section (there's also 2FA support!). Anyways, there's no easy way to get it working with that site in particular :/

You can request youtube-dl to add that site by submitting an [issue here](https://github.com/ytdl-org/youtube-dl/issues) (make sure you follow the format to a T because they can be particular about that). But don't bank on them adding it anytime soon since they have hundreds of site suggestions lol

Anyways, feel free to open up an issue if you encounter anything else, always happy to help!

**Comment by maltokyo** [comment]
Thanks a lot for the details!
