### ISSUE TITLE
Alternative to youtube-dl

### ISSUE THREAD

**Issue by Typhonragewind** [Tzahi12345/YoutubeDL-Material#234]
Hello!

Would it be possible to include the option to change the youtube-dl binary to youtube-dlc? Youtube-dlc is a fork of youtube-dl with more active development/maintenance of sites.
Should work the same as youtube-dl, i think.

link to the project> https://github.com/blackjack4494/youtube-dlc

**Comment by Tzahi12345** [comment]
Interesting, right now we don't call the binary directly, but we've been looking to use a better downloading system so youtube-dlc could be used once that process starts (see #111)

**Comment by Tzahi12345** [comment]
Not sure where to post this, but youtube-dl and youtube-dlc just got DMCA'd on GitHub

https://github.com/ytdl-org/youtube-dl

https://github.com/blackjack4494/youtube-dlc

![image](https://user-images.githubusercontent.com/707413/97067921-d0f31e80-1590-11eb-8bfd-2405c9e28a29.png)

**Comment by RashiqAzhan** [comment]
Wow. Imagine my surprise after coming to the internet after a fortnight to see a FOSS as useful as youtube-dl being taken down.

I hope @ytdl-org and @blackjack4494 move to some other VCS. Selfhosted Gitlab or Gitee maybe?

Mr. Tzahi, do you think your work is in peril now? Since, as of writing, directly depends on youtube-dl.

**Comment by Typhonragewind** [comment]
This is a shock indeed, I didn't even know it was possible.

Tzahi, I'm no coder, but if there is anyway i can help just let me know.

**Comment by Tzahi12345** [comment]
>Mr. Tzahi, do you think your work is in peril now? Since, as of writing, directly depends on youtube-dl.

I don't think so. The RIAA went after youtube-dl and co. because they had copyrighted materials in their docs. We don't, so we're good on that front. My only fear is getting a copyright strike from Google for using "Youtube" in the title. If this ever happens we can brainstorm a new name.

>Tzahi, I'm no coder, but if there is anyway i can help just let me know.

I think we're good! Let's just keep an eye out, I assume youtube-dl and youtube-dlc will start another main repo. The only code which is broken due to this is youtube-dl autoupdates. Should only require a simple fix.

If you have some free time, check out the [translations dashboard](https://hosted.weblate.org/projects/youtubedl-material/ytdl-material/), you can add new languages if you're fluent in something that isn't on that list

**Comment by Typhonragewind** [comment]
> If you have some free time, check out the [translations dashboard](https://hosted.weblate.org/projects/youtubedl-material/ytdl-material/), you can add new languages if you're fluent in something that isn't on that list

Started doing that. Wish i could leave comments on my translation though xD. Portuguese can be very contextual and some things don't make sense to translate.

**Comment by frumpymoons** [comment]
Here is the new youtube-dlc repo
https://github.com/blackjack4494/yt-dlc

**Comment by Tzahi12345** [comment]
Given youtube-dl's lack of a new official repo, I'm currently working on making youtube-dlc the default!

**Comment by adan89lion** [comment]
@Tzahi12345 I recommend other projects that can handle and download YouTube videos, like [you-get](https://you-get.org/)  and [annie](https://github.com/iawia002/annie). They can act as a temporary alternatives to YouTube-DL.

**Comment by Tzahi12345** [comment]
@adan89lion The way the current downloading functionality works, a youtube-dl alternative must be a drop-in replacement for youtube-dl. That is, the syntax and functions must be the same (though new features that don't conflict are not an issue)

I have just pushed an update ([see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/b323b548ca6047978e4a9779796bb9e1b51129ca)) that defaults the downloader to youtube-dlc. Pull the latest `nightly` and see if it works on your end!

**Comment by neilyboy** [comment]
> @adan89lion The way the current downloading functionality works, a youtube-dl alternative must be a drop-in replacement for youtube-dl. That is, the syntax and functions must be the same (though new features that don't conflict are not an issue)
> 
> I have just pushed an update ([see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/b323b548ca6047978e4a9779796bb9e1b51129ca)) that defaults the downloader to youtube-dlc. Pull the latest `nightly` and see if it works on your end!

Latest works for me and youtube-dlc thank you so much!
