### ISSUE TITLE
Add sidebar items for "Audio" and "video" browsing

### ISSUE THREAD

**Issue by jo-me** [Tzahi12345/YoutubeDL-Material#255]
Just an idea:

Instead of showing the downloaded items beneath the URL textbox you could add sidebar items for video/audio browsing of the downloaded content.

The content beneath the URL textbox is called "my videos" right now but contains audio and video content. That area could be reused to show the recently downloaded videos (e.g. limited to the last 10 or so) and renamed to "recent downloads".

**Comment by jo-me** [comment]
@Tzahi12345  would you accept a PR for this?

**Comment by Tzahi12345** [comment]
Ah sorry for the late response, yes I would but with a bit of a twist: I'd prefer it if the home page "my videos" section still served as the location for viewing downloaded videos (in the latest nightly it's even paginated), but with something like a dropdown that has 3 options:
* Video and audio
* Video only
* Audio only

 Dedicated pages for it seems overkill, and you can currently use "my videos" to view recently downloaded videos, just switch to sort by download date. And since it's paginated, it'll show 10 videos my default so no more issues like #225. Does that sound OK or do you envision it as looking different?
