### ISSUE TITLE
Ability to choose video quality for subscriptions

### ISSUE THREAD

**Issue by DarkSkyGhost** [Tzahi12345/YoutubeDL-Material#269]
Right now the subscriptions are downloaded only in the 1080p or lower quality.

Would be nice to have ability to choose max subscription quality (including 4k).

**Comment by Tzahi12345** [comment]
You are right in that it usually downloads 1080p and that's because the default behavior is to look for the highest quality mp4 (usually 1080p). It's a bit of a stylistic decision, but we do allow you to change it if you want.

Simply add the custom arg `-f,,bestvideo+bestaudio,,--merge-output-format,,mp4` and you'll get the absolute best quality. I've thought that maybe this deserves a dedicated option, just not sure how many users want this, and from those who do want it, how annoying it is to add the custom arg.

**Comment by DarkSkyGhost** [comment]
As I consider myself a dumb user and totally unfamiliar with youtube-dl, I'd definitely want an option to choose download quality - either globally, either per-subscription :)

**Comment by DarkSkyGhost** [comment]
Also, would be great to be able to add custom args to subscriptions globally in the settings.

Currently through settings I can set custom args only for downloads on home screen, correct?

**Comment by Tzahi12345** [comment]
>As I consider myself a dumb user and totally unfamiliar with youtube-dl, I'd definitely want an option to choose download quality - either globally, either per-subscription :)

That's totally fair! I feel like a large portion of people who use this just don't wanna mess with youtube-dl and its intricacies, they just want to download videos and not worry about anything else.

I've gone ahead and added this feature, [check out the latest commit for details](https://github.com/Tzahi12345/YoutubeDL-Material/commit/8938844ffad704bca81fa339467526083e1404bc). It's per-subscription as of now.

>Currently through settings I can set custom args only for downloads on home screen, correct?

You are correct. I can expand the global custom args to subscriptions, I'm a bit worried that some users may not want this. Open up an issue and we'll see how people react, if no one throws a fuss I'll gladly add that in (won't be hard at all). Anyways, thanks for the suggestion!
