### ISSUE TITLE
how to use it on windows?

### ISSUE THREAD

**Issue by mahdisky** [Tzahi12345/YoutubeDL-Material#312]
hi
how to install and use it on windows 10 ?
is it necessary for run  to install docker?

**Comment by Tzahi12345** [comment]
It isn't necessary, it's just recommended as it makes the installing and updating process a lot simpler. But if you don't want to deal with Docker, that's ok, first [follow the instructions here](https://github.com/Tzahi12345/YoutubeDL-Material#installing).

But, it won't work out of the box and it's because you don't have the ffmpeg binary available. [Gyan.dev](https://www.gyan.dev/ffmpeg/builds/) builds them, here's a [direct download link](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip) to a zip that has ffmpeg and some other stuff too. You only need ffmpeg so ignore the rest in the zip, just go into the bin folder to find `ffmpeg.exe`.

Drag that file into the `backend` folder and start up the server. You should be able to access it at port `17442` and download away! Let me know if you run into any issues along the way.

**Comment by alexvermaning0** [comment]
can't find the "backend" folder. im not the one who made this question but to open a new ticket is not nessecery (thats what i think about it.)

**Comment by Tzahi12345** [comment]
Closing as I assume this is resolved. Let me know if this isn't the case, and I'll re-open.
