### ISSUE TITLE
Downloading the same video 2-3 times

### ISSUE THREAD

**Issue by neldonado** [Tzahi12345/YoutubeDL-Material#327]
![image](https://user-images.githubusercontent.com/46225185/107032102-1ca88d00-6768-11eb-80d7-42b7966edee7.png)
I am having a strange issue where it is downloading my subscribed channel videos 2-3 times each. I just realized this has been happening for quite a while and it's taking up a lot of space.

**Comment by Tzahi12345** [comment]
Do you have a custom output set for the subscription? Is there any change in the file name? Or is this just a UI issue (in this case there wouldn't be a whole lot of extra space usage)?

**Comment by GlassedSilver** [comment]
Maybe not related, but there's also an issue with subs of Twitch channels where at first a partial video is downloaded and then separately the VOD, but that one in full length.

**Comment by nivagator** [comment]
I'm getting the same behavior on the home page. I do not see duplicate files downloaded, but they are appearing twice on the home page.

**Comment by QrchackOfficial** [comment]
I have the same situation. Looking at my local_db.json, the videos are listed in both "files" and "subscriptions", and removing the entry in "files" just causes it to be added again upon restarting the Docker container.

**Comment by QrchackOfficial** [comment]
Also looks like removing the entry from "subscriptions" by hand fixes it.

**Comment by Tzahi12345** [comment]
@QrchackOfficial this actually helps quite a bit, it's probably due to editing the subscription and not stripping out the videos which we add when editing (that's my guess but I'll take a look at the code today)

**Comment by Tzahi12345** [comment]
Bug fixed! [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/7be90ccd94d5455bb6ad56392af4633ae69e8a5a). Basically the issue is with local_db enabled, the DB is cached in RAM and so when we would append videos to a subscription before sending it out, the cache would get updated as well (as it pointed to the same object). The cached DB eventually was written back to disk and it carried the videos with it.

Additionally, the logic to append subscription videos to a list of user files was also left behind. Both of these combined caused this issue, now it should not anymore (even if the `videos` property still exists in the `local_db.json` for subscriptions).
