### ISSUE TITLE
Suggestion: Option to remove arg globally

### ISSUE THREAD

**Issue by randomnameforgithub** [Tzahi12345/YoutubeDL-Material#328]
At the moment, we can use custom arg for each download.

However, we can only add global custom arg and not remove custom arg. (e.g. remove --write-info-json --print-json) 

Maybe good to have this feature?

**Comment by Tzahi12345** [comment]
I've thought of adding a feature of running a custom youtube-dl command, the only caveat is that the video player would not be able to work under this scheme because `--print-json` for example is required for that to work, and any file extension that isn't mp3 and mp4 will break the app. Would this fit your use case?

`--write-info-json` can be disabled by going into the downloader tab and unchecking `Include metadata` but it isn't recommended.
