### ISSUE TITLE
Thumbnails not loading in My Videos

### ISSUE THREAD

**Issue by BeecherNetworks** [Tzahi12345/YoutubeDL-Material#362]
Just installed using Docker, no changes made to Settings yet, downloads working fine but for some reason the thumbnails aren't displaying under My Videos. Permissions seem fine too. SRC URL looks like this. Do I need to configure something?

https://HOSTNAME/api/thumbnail/BLAH.webp

**Comment by Tzahi12345** [comment]
Can you look in your browser console to see if it's 404'ing those URLs for whatever reason?

They should work automatically, both webp and png.

**Comment by BeecherNetworks** [comment]
I did, it is. Sorry, should have mentioned.

**Comment by Rakshasas** [comment]
I would like to add some information to this issue as I am experiencing the same issue as well.

Just a bit of detail about my setup, I am running this from a RaspberryPi, with the hostname of "raspberrypi" using docker / docker-compose.

If I navigate to the site with **http://raspberrypi.lan:8998**, I can see all the thumbnails with no problem. 

However, I have a reverse proxy setup as well, and if I navigate to the same site through the reverse proxy: **http://youtube-dl.raspberrypi.lan** I do not see thumbnails. They show a 404. All the functionality works otherwise regardless of the way I access the site.

If I attempt to load the specific image that 404'ed. I see a message similar to this:

```
Cannot GET /api/thumbnail/video/ImageNameHere.jpg
```

Disclaimer, I have not yet implemented https, and since OP omitted the port from his sample address it's possible a reverse proxy is in play there as well.

The only setting I changed is the URL, and I did that _after_ I found that the thumbnails did not work. 

![image](https://user-images.githubusercontent.com/1557984/113730065-8c35ec80-96c5-11eb-868f-b684374a9268.png)

**Comment by BeecherNetworks** [comment]
I am indeed behind an Nginx proxy. Didn't think to change the hostname as it was being generated correctly in the source code, but changing it does indeed correct the thumb problem. I haven't changed the port, which makes it odder still.

**Comment by Rakshasas** [comment]
So you change it and now it works for you? I wonder why it made no difference for me.

**Comment by alextartan** [comment]
I had the same issue while trying to access it through an apache proxy. Turned out to be a URL encoding issue.

Adding `AllowEncodedSlashes NoDecode` fixed it:

```
    AllowEncodedSlashes NoDecode     

    <Location />
        ProxyPass http://192.168.x.y:17442/
        ProxyPassReverse http://192.168.x.y:17442/
    </Location>
```
