### ISSUE TITLE
Option to change the download path in each download (single or subscription)

### ISSUE THREAD

**Issue by pablocp19** [Tzahi12345/YoutubeDL-Material#374]
Hello, first of all congratulations on this great software.
As an improvement, I would propose to be able to choose directly in an input box the download path in each section (subscriptions and single video) and in the case of subscription to be able to prevent channels and playlists folders from being created. Although it does not come by default that it is an option to be able to avoid these folders.

**Comment by Bart39** [comment]
I agree, great software.
I would also like the option of turning off the folders that get automatically created as i would rather have all my subscription in the same base folder and then use the custom file output options to specify the path

**Comment by Tzahi12345** [comment]
This is actually already possible, if you enable advanced download mode in the settings you should be able to edit the path for an individual download.

You can also edit individual subscriptions and change their default output path.

@Bart39 You can definitely create a separate issue for this request, there's some code already there that handles some of this (related to [categories](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Categories)) though it hasn't been expanded to allow for *any* path for downloads otherwise.
