### ISSUE TITLE
Unraid: Can't open the webUI

### ISSUE THREAD

**Issue by miguelarios** [Tzahi12345/YoutubeDL-Material#386]
I am trying to open the webUI after updating to 4.2, and it doesn't open up. I have removed the docker image to redownload it, but nothing works. I see the logs are showing all good on port 10000. I also don't have another docker on the same port.

```
[33mwarn[39m: --minUptime not set. Defaulting to: 1000ms
[33mwarn[39m: --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
2021-05-24T14:19:09.553Z INFO: youtube-dl successfully updated!
2021-05-24T14:19:09.558Z INFO: YoutubeDL-Material v4.2 started on PORT 10000
```

**Comment by frezeen** [comment]
i miss setting page when update to 4.2, nothing happen when click settings. docker version for me too

**Comment by GlassedSilver** [comment]
Which template are you using? Afaik there's multiple ones out there and I withheld releasing the one I made myself because I didn't want to do it prematurely and then support a lot of people's paths changing or something.

Maybe show me your template's settings?

I can most certainly try to help here. That being said, I would HIGHLY recommend using the nightly tag, because the release channel's version is really dated by now and nightly isn't really nightly, but more like a carefully released beta channel.

There's bit of wonkiness, but I would say the foundation changed by so much it's really worth going with the nightly builds which just up the UX so much.

**Comment by miguelarios** [comment]
I deleted it and reinstalled it months later and it seems to be working now!
