### ISSUE TITLE
Playlist : option to play songs in random order 

### ISSUE THREAD

**Issue by busemorose** [Tzahi12345/YoutubeDL-Material#399]
Hello, I would love to have the option to play randomly songs of a playlist. I didn't find anything about this so here are some suggestions, it could be either:
- in the playlist "edit" menu. An on/off button on the top right labelled "Random" or with an icon
- on the playlist interface, add an icon on the left on volume button

Thank you for the awesome app!

**Comment by Tzahi12345** [comment]
Just implemented this! I took your first approach, since it keeps the player a little bit clean. Of course, I'm open to changing this in the future. If you're on Docker, pull the latest `nightly` and you'll be able to make your playlists shuffle. [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/9f908aa3fc1f0a748706da00a29dd14f6537279c)

**Comment by busemorose** [comment]
Thank you very much, it works perfectly! However, I noticed that adding audio files through "Add content" does not trigger the "Save" option. I'm not sure if (i) it was already there in the `nightly` image (I was using `latest`), (ii) if it results from your last commit, or (iii) it is a issue on my setup.

It is not a problem for me as I can save by checking/unchecking the random box, but it is only a workaround. Please tell me if I should open a new issue or something, I'm not used to GitHub functioning.

**Comment by Tzahi12345** [comment]
Just reproduced and fixed it! `nightly` should be updated in about an hour or so.

**Comment by busemorose** [comment]
Thank you for the nice work!
