### ISSUE TITLE
[FEATURE] limit simultaneous downloader instances

### ISSUE THREAD

**Issue by andreicociuba** [Tzahi12345/YoutubeDL-Material#410]
**Is your feature request related to a problem? Please describe.**
I am trying to import via curl API requests my entire youtube subscriptions list. it's black magic held together with awk, cut, sed, grep and a greybeards eyelash.
The problem is that very quickly degenerates into 100++ instances of youtube-dl trying to download not just channel info json, but videos, even when i specify to not download everything, just everything less than x days old. It just is A LOT.

this causes youtube-dl to quickly get rate limited by google itself, then it's slow, and then there's a bunch of messages in the cli of the docker container that promises are unfulfilled. I am no node guru, but i suspect the download somewhere times out in the internal logic.

i also suspect that these errored out videos never get retried, but i haven't actually checked.

**Describe the solution you'd like**
I would like a feature to limit the downloading instances of youtube-dl to a specific number.

**Additional context**

**Comment by andreicociuba** [comment]
also my server is old, underpowered and overheated anyway, so having hundreds upon hundreds of youtube-dl trying to do anything makes the cpu cry.

**Comment by Tzahi12345** [comment]
You can add the following to the subscription's args `--sleep-interval,,60`:

![image](https://user-images.githubusercontent.com/707413/127727986-bd49a0a7-a9e2-4539-a0f1-08218418928f.png)

But, this should be a global setting in the GUI as it's quite commonly used. Because #379 is quite related, I'm going to close this issue and we can keep track of this specific feature request there.
