### ISSUE TITLE
[FEATURE] SponsorBlock integration

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#414]
**Is your feature request related to a problem? Please describe.**
Yes, it's related to #189 
It takes the convenience need to skip parts of videos, but in this way we could do it at play-time rather than download-time and hence: non-destructive, for anyone who feels like a) not setting trim times manually and b) for even more convenience, since the database is REALLY big. Unlike back in 2020 when I commented and suggested using it I've been a very happy user of it now for months and let me tell you: I don't want to use YouTube without it anymore! :D 

for it to work we would however need to be able to access videos at least ALSO through a second way: by constructing the video page from the source URL. e.g.:

**Describe the solution you'd like**
https://myyoutubedl-material-instance.com/watch?source=https://youtube.com/watch?v=YOUTUBEVIDEOID

Rinse and repeat for any other supported site.

This would be needed for the plugin to parse the URL of a YTDL-M instance.

SponsorBlock also lets you download the database and self-host it! So one could integrate the DB directly into ytdl-m as well, however: at least ALSO providing the alternative URL schema would have another benefit: it would allow for automated requests to backups of a given URL without interacting much with the GUI and to prefix a link that reports as deleted video automatically a local mirror we got in whatever fun little project we might have that links to YouTube videos.

Think how the Internet Archive does it! :)

https://web.archive.org/web/*/example.com

Another benefit is that we could always "blindly" try to pull up a video from an instance without knowing anything about it. No need to know the internal video ID, the official one can be perfectly ample reference.

**Additional context**
Today's random context is that I'm having Nutella croissants at the moment. Is this relevant?
No, of course not, but does this look better than an empty spot in my request? Oh yes, it does!

**Comment by Tzahi12345** [comment]
This one is easy to implement, but there are several ways to go about this, which matters particularly because the CSV file they have is over 1 million lines long and over 500MB. The two approaches that I see are:
* On startup (or first video download), load the CSV into memory and convert to a JSON object for performance
  * Benefit: great performance, but high memory usage
  * Optional: load the file into DB for even better performance (and compression)? May make it harder or more costly to update but querying will be fast and we won't have to load the file into RAM
    * One caveat here is that without MongoDB, the DB would blow up to insane proportions. We'd need special logic to either use the CSV file when MongoDB isn't present, or save the converted JSON to a separate file
* Every time a video downloads, load the file, search through it, and unload when finished
  * Benefit: straightforward, low memory usage (except when downloading), but also low performance, taking *at least* seconds if not minutes to go through the DB

In either scenario, the file should be already downloaded to disk one way or another.

Once we get the start and end times, we can use the existing `cropFileSettings` parameter for downloads to allow for *removing* certain parts of a video instead of *keeping* a specific portion [like so](https://superuser.com/a/863451).

>Another benefit is that we could always "blindly" try to pull up a video from an instance without knowing anything about it. No need to know the internal video ID, the official one can be perfectly ample reference.

Not sure I understand, do you mean we can figure out if a video is deleted or not before downloading? I don't see a column in the CSV for that though.

So I think overall this would be a great feature, we just need to decide which path to go down.

Hope the croissants treated you well :) A bit of a rare sight here across the Atlantic

**Comment by ajayyy** [comment]
Note: it is possible to query the API in a privacy respecting way instead of using the CSV https://wiki.sponsor.ajay.app/index.php/API_Docs#GET_.2Fapi.2FskipSegments.2F:sha256HashPrefix which will always be up to date (instead of data from whenever you last downloaded the CSV)

That would be preferable in a self-hosted application like this since bandwidth costs $ and there would be many users pulling the csv often.

**Comment by GlassedSilver** [comment]
You can just self-host the backend server of SponsorBlock....

And cropping? Why? Let's not crop, but just integrate the UI for skip and unskip commands and the settings (what to skip, what not to skip, what to offer to skip manually) 

cropping = destructive. Let's not do this, please. You save a few megabytes depending on what you like skipped and end up with the headaches of possible false positives.

**Comment by GlassedSilver** [comment]
> Note: it is possible to query the API in a privacy respecting way instead of using the CSV https://wiki.sponsor.ajay.app/index.php/API_Docs#GET_.2Fapi.2FskipSegments.2F:sha256HashPrefix This will always be up to date (instead of data from whenever you last downloaded the CSV)
> 
> That would be preferable in a self-hosted application like this since bandwidth costs $ and there would be many users pulling the csv often.

Good point! One question: maybe there could be delta updates? It would possibly be a happy middle ground.

**Comment by Tzahi12345** [comment]
@ajayyy Oh awesome! This makes my two proposed solutions totally worthless, great to hear this is possible :)

@GlassedSilver I didn't even consider skipping client-side, in fact this could probably be done without any backend work. Maybe just a checkbox in the player that says "skip ads" if they are detected, and any video timeline navigation into one of the sponsor sections will disable the checkbox (as the user clearly wants to see them).

**Comment by Tzahi12345** [comment]
Went for the more common approach that streaming sites like Netflix use:

![image](https://user-images.githubusercontent.com/707413/128630970-86c6ff56-57b3-4766-b544-53ce69b973e5.png)

There's a new setting that enables this feature (off by default, don't want to abuse @ajayyy's API). [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/8b1a1a56e354c81175162388549e79eec200faa5).

Let me know your thoughts!

**Comment by GlassedSilver** [comment]
The problem I see with this is that it completely circumvents the flexibility that SponsorBlock has as an extension.

![image](https://user-images.githubusercontent.com/1912133/129487395-e01bd330-0402-4bcc-8f77-f3dd3f7ec521.png)

These are my settings for example.

Also, the nice thing about the extension is that it will color code segments in the seek bar as well as let you customize which things to display. I really recommend checking out the extension and then going to settings like so:

![image](https://user-images.githubusercontent.com/1912133/129487474-1cb433b2-7417-4846-b890-2becb8c7a62b.png)

![image](https://user-images.githubusercontent.com/1912133/129487481-66fe7abd-496c-4e47-9165-5dba9adae197.png)

This really sets it apart from anything I've ever seen. Also, the integrated stats for how many minutes have been skipped already are just SOOOOOO nice. It lets you quickly see how well it works for you. Absolutely love what @ajayyy has done here. Even letting users host their own server is just... Man. I love you for that! (not using it ATM, but boy am I glad that the extension could still work with a database dump if your offering ever were to get taken down for whatever reason)
