### ISSUE TITLE
[BUG] Losing entire database if docker or server shuts down or crashes

### ISSUE THREAD

**Issue by Goolashe** [Tzahi12345/YoutubeDL-Material#425]
**Describe the bug**
db.json file is purged, losing all subscriptions/playlists and list of videos if something stops the docker from running while the database is being modified.

**To Reproduce**
Shut down or crash the docker/server while it is modifying db.json as new vides are downloaded.

**Expected behavior**
The database not to be purged :)

**Environment**
- YoutubeDL-Material version 4.2

**Additional context**
This has happened half a dozen times or so over the past half year, with this happening twice recently (kernel panic, then separate server shut down a couple days later). From what it looks like, the file is erased/wiped and then written with the new updated info as videos are downloaded, but, if for some reason the server shuts down between the wipe and re-write, you lose everything.

Maybe the database could be automatically backed up in a separate file each time it has to modify the main db.json so everything isn't lost because of a kernel panic, power loss, etc. This issue seems to have a high risk of happening if you have a lot of channels or playlists monitored, or recently added a lot.

**Comment by GlassedSilver** [comment]
I know this doesn't help retroactively, but I can only recommend moving your setup to use mongoDB, because it GREATLY increases reliability and speed.

It's still not ideal, personally I have my qualms against using a db that's not relational, however I see why mongoDB is used at least now, because it **IS** easy to move to it from the existing json structure.

If you need assistance moving it, I can help you. In any case, make sure you use the nightly build of ytdl-m, the last release channel version is from last December and a LOT has happened since then.

I'd also advise to make cron-jobbed backups of the mongodb database once you set that up, as for how that works excactly I'd still have to figure that out myself, I'm just not very experienced with mongoDB, but you can always use mongoDB Compass to make manual backups and inspect your database manually on demand. VERY handy to have and that's also what @Tzahi12345  uses. :) 

In any case if I missed anything or you need further help with this, let me know. I've been through this plenty enough to be able to offer help. Hooray!

the local db structure with json files just doesn't scale. In a release that's not nightly anymore (4.3) this limitation of using a local file structure rather than a database backend would probably be clearly communicated.

**Comment by Tzahi12345** [comment]
@GlassedSilver is correct in that MongoDB solves this issue. #422 should do the same as backups/restoring of the database will be done through there as well.

**Comment by brokengdnb** [comment]
![Screenshot 2022-04-18 at 21 15 09](https://user-images.githubusercontent.com/61773461/163854370-5546f954-89a9-41b2-88be-0c4fb9d344aa.png)

hi, my problem is there is not even option for mongoDB in settings: using v4.2 

 - any ideas hot to enable mongoDB?

**Comment by GlassedSilver** [comment]
> ![Screenshot 2022-04-18 at 21 15 09](https://user-images.githubusercontent.com/61773461/163854370-5546f954-89a9-41b2-88be-0c4fb9d344aa.png)
> 
> hi, my problem is there is not even option for mongoDB in settings: using v4.2
> 
> * any ideas hot to enable mongoDB?

You’re not on the nightly releases which are by FAR the better way to run your instance. :)

If you use docker to install YTDL-M, just append a `:nightly` to your image. :)

Also I notice this issue is still open despite this having been resolved by going mongodb. I’ll close this issue therefore.
