### ISSUE TITLE
[FEATURE] Consolidation of duplicate videos with unique descriptions or thumbnails

### ISSUE THREAD

**Issue by jonathanm-ur** [Tzahi12345/YoutubeDL-Material#430]
**Is your feature request related to a problem? Please describe.**
Due to youtube's ever changing recommendation algorithm, many channels will regularly change the thumbnail and description of a single video, resulting in multiple downloads for what is actually the same video

**Describe the solution you'd like**
Only display the latest thumbnail and description, don't redownload a new copy of the same video. Ideally the history would be viewable somehow, so you could see all the different historical thumbnails and descriptions if you wanted, or clear them.
Perhaps hashes could be added to the video metadata and used to detect dupes.

**Additional context**
This is a long standing issue, and there are some channels that automate new titles and thumbnails at regular intervals for the express purpose of using that info as data. One of those is https://www.youtube.com/watch?v=phqWpgA3u9w and the youtubedl detection causes a new copy of the same file to be downloaded every few hours or more.

**Comment by GlassedSilver** [comment]
#415 probably related. Can you verify this is a redundant data issue rather than possibly just redundant displaying?

**Comment by GlassedSilver** [comment]
As for catching alt titles, descriptions and thumbnails... Seems like a fun idea, because more data usually means better context, searchability, etc... Could possibly be linked to the functionality to re-download new videos (which is an existing feature, although afaik it should clear the old one).

We'd then store the historical grabs of title, description and thumbnails in arrays in the database and the second json file with it's new metadata could possibly be named <video-filename>.info2.json and respectively <video-filename>.webp/jpg/... for the thumbnail file.

Maybe limit to a history of 5 items, idk.

We need re-pulling of older downloads periodically anyways, because it helps us grab subtitles that may have been added after the fact and another good thing about re-grabbing metadata is that fresh uploads (as subscriptions tend to go for once you've grabbed all of the backlog) do not have a lot of views, so the "views" field in the json (which might be interesting data to analyze and search by later on in other features) is usually incriminatingly low and not very telling.

Sorry for the long tangent. :O

**Comment by jonathanm-ur** [comment]
> #415 probably related. Can you verify this is a redundant data issue rather than possibly just redundant displaying?

I read that thread pretty thoroughly, it looks to me like the issue there is that multiple thumbnails are linked to the same download that only exists once in the dataset.

The issue I'm discussing here is not a bug at all, and can easily be shown just by downloading the video I linked. Simply download it, then download again a few hours later. The same video file will be fetched, with a totally new title and thumbnail.

That's why I posted a feature request instead of a bug report.

**Comment by arithxp** [comment]
I know a channel that changes its thumbnail or title after a few hours of a video.
It may have been uploaded as a recommended video or the title may have been changed because it is inappropriate.
In this case, multiple videos are created with the same video address but different titles.

**Comment by GlassedSilver** [comment]
Interesting finding.

What are your guys' archive settings like? Have you checked "Use youtube-dl archive"  in Settings > Downloader?

**Comment by arithxp** [comment]
> 
> 
> Interesting finding.
> 
> What are your guys' archive settings like? Have you checked "Use youtube-dl archive" in Settings > Downloader?

Yes. I think the solution is to use youtube-dl archive.

**Comment by GlassedSilver** [comment]
When I try to download the video all I get is this error:

`ERROR: unable to download video data: <urlopen error [Errno -3] Try again>`

As for the issue itself: Good if that fixes it for you, nobody likes redundant gigabytes or worse :P

As for the feature request though: still think it's really interesting! Not sure what @Tzahi12345 thinks, but I think this has potential.
The database schema has to be extended eventually anyways and storing alt titles, descriptions and thumbnail file references in respective arrays should be pretty doable. (we should definitely diff against existing values so we don't blindly re-save the same values blindly for however many n go-arounds the user has set :D )

**Comment by jonathanm-ur** [comment]
> When I try to download the video all I get is this error:
> 
> `ERROR: unable to download video data: <urlopen error [Errno -3] Try again>`

Hmm. I've never tried to put just the single video in, I'm subbed to the channel. Does the link work in a browser?

**Comment by jonathanm-ur** [comment]
![image](https://user-images.githubusercontent.com/64561015/130500526-059507bf-489a-4ae7-b225-82529db017c2.png)

**Comment by jonathanm-ur** [comment]
> .
> 
> What are your guys' archive settings like? Have you checked "Use youtube-dl archive" in Settings > Downloader?

Nope. I must confess, I haven't researched what effect that has.

**Comment by GlassedSilver** [comment]
> > When I try to download the video all I get is this error:
> > `ERROR: unable to download video data: <urlopen error [Errno -3] Try again>`
> 
> Hmm. I've never tried to put just the single video in, I'm subbed to the channel. Does the link work in a browser?

Yeah it does.
Maybe it's iffy because the title changes mid-through the download and just doesn't finish in time before that happens on my end. Idk

What do your storage settings look like btw?  As in what path and file naming rules do you use?

**Comment by jonathanm-ur** [comment]
> What do your storage settings look like btw? As in what path and file naming rules do you use?

Apparently default. I can't find anything other than 
![image](https://user-images.githubusercontent.com/64561015/130502589-7c60bf80-41fb-4b04-ad1f-4f81a12a8226.png)

**Comment by GlassedSilver** [comment]
I run with my own logic here, so maybe my naming helps mitigate this as well? Not sure, at least @arithxp seems to be more fortunate with setting the archive usage to on, could you try that out? It's really helpful and beyond helpful it also is nice to keep an overview of all that you've downloaded in files that are easily humanly readable but also machine-processable without needing to hook into the backend server.

**Comment by jonathanm-ur** [comment]
>  It's really helpful and beyond helpful it also is nice to keep an overview of all that you've downloaded in files that are easily humanly readable but also machine-processable without needing to hook into the backend server.

Is there documentation describing what the archive mode actually does? I poked around a little on this github and couldn't find any. I'm gunshy about changing any settings, too many long hours recreating data that blew up after something crashed and erased the db.json files once again. I'm now migrated over to mongo, so theoretically the risk is less, but I'm hesitant to poke the bear too much.

**Comment by arithxp** [comment]
> Is there documentation describing what the archive mode actually does?

https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-download-only-new-videos-from-a-playlist
it's youtube-dl feature

**Comment by jonathanm-ur** [comment]
> it's youtube-dl feature

Yeah, I found that. What I don't know is how it's implemented in this container. I.E., what happens with the workflow when that option is enabled? What is different in the user experience with that option checked?

Maybe I'm paranoid, but when someone presents an "archive" option, it traditionally means that older content will no longer be presented in the same interface or location, and moved to a long term storage location. I don't want any of my files moved, nor do I want the interface where I interact with them to change. I have things set up where the channels are available in emby, for secure viewing anywhere.

**Comment by GlassedSilver** [comment]
> 
> 
> > it's youtube-dl feature
> 
> Yeah, I found that. What I don't know is how it's implemented in this container. I.E., what happens with the workflow when that option is enabled? What is different in the user experience with that option checked?

Alright, I see where you're coming from, you're much like me. You wanna know what something does before you set something to a non-default value. :P 

Here's the deal: when we pass archive.txt's to get created we write the archive.txt file like this:

1. **Subscriptions:** We place an archive.txt in the `/subscriptions` directory in the archives sub-directory. e.g.:
`/subscriptions/archives/akidearest/archive.txt`
2. **One-off downloads:** We place a merged version of archive.txt into the `/video` directory. This is so that we don't end up with archive.txt's scattered all over the file system next to where we store the video files. AFAIK the logic applies to /audio respectively in the same manner, but I don't use audio, so... don't quote me on that, ask @Tzahi12345, but I doubt it's any different expect for audio instead of video as the keyword in this:
`/video/merged_video.txt`
Another bonus is that we always know where to expect that file and that this file works universally without doing a large run-around for possibly hundreds or thousands of directories! :)
3. We also store an `archive_video.txt` of merged nature in `/appdata`. As for the exact difference between those... I gotta admit I don't know atm, so maybe we ask @Tzahi12345 for this, but this should give you a good impression of what this setting does.

If I missed anything I'm sure you can fill in Tzahi. :)

> Maybe I'm paranoid, but when someone presents an "archive" option, it traditionally means that older content will no longer be presented in the same interface or location, and moved to a long term storage location. I don't want any of my files moved, nor do I want the interface where I interact with them to change. I have things set up where the channels are available in emby, for secure viewing anywhere.

I see what you mean, but no, this is just youtube-dl terminology and has got nothing to do with moving files around. :) 

I used to desire viewing my downloads in Jellyfin (or Plex before I moved away from it) myself, also the source of some of my previous conceptual ideas for this application. So you have my sympathy, previous and current support on wanting that workflow. Personally I now call YoutubeDL-Material my home interface-wise for its downloads, but I get your desire and I myself support it. I'm sure Tzahi feels no different, the beauty of YoutubeDL-Material is that it's so adaptive/that that is the goal we continually try to improve on! :)
