### ISSUE TITLE
Heroku Deployment not working

### ISSUE THREAD

**Issue by akhil-rana** [Tzahi12345/YoutubeDL-Material#446]
### Deploy using heroku badge is not working anymore. 

 Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

1. Deploy to heroku using the badge in readme.md

**Environment**
- YoutubeDL-Material latest and v4.0 both are not working on heroku

**Comment by GlassedSilver** [comment]
I have no idea how Heroku works, but I'd suggest switching to the `:nightly` tag.

The release channel is VERY outdated, maybe that causes issues.

Feel free to follow up if I couldn't help so far. :)

**Comment by GlassedSilver** [comment]
Maybe try again now. If Heroku automatically goes by the Docker-compose then it should now grab the nightly channel by default.

If it doesn't help let me know, please and I'll try to see what I can do.

**Comment by akhil-rana** [comment]
I've tried deploying again but same error.

And I don't think heroku deployment uses docker-compose at all. It's just deploying a vanilla node app or something. Which makes me wonder if heroku deployment ever used to work? 
Since I tried older releases and tags too. Not too old though.

**Comment by Tzahi12345** [comment]
Currently looking into this. It's a legitimate bug, and has been there since v4.2 or so and I hadn't redeployed heroku so I wasn't aware of it. The good news is there's a way to deploy to heroku using a Docker image, the bad news is I haven't figured out how to get it to work, especially with the button. Will keep you updated on this!

I've asked for [help on SO](https://stackoverflow.com/questions/69277769/heroku-deployment-keeps-building-with-nodejs-instead-of-using-heroku-yml) so we'll see how that turns out.

**Comment by Tzahi12345** [comment]
Took a while but I got a response on SO! Turns out it was a syntax issue, of course :P See #602

Anyways, Heroku deployments should work now and it uses Docker, which makes my life a lot easier. Thanks for the bug report @akhil-rana!
