### ISSUE TITLE
Apple Shortcut creation (using bookmarklet logic)

### ISSUE THREAD

**Issue by u0a1009** [Tzahi12345/YoutubeDL-Material#477]
Hello
I'd like to make a iphone shortcut to download youtube videos fast.
So I got bookmarklet's javascript and changed into plain url like this = https://[Your Server]/%/home;url=' + [Encoded URL] + ';audioOnly=false
But it didn't work. (I encoded url via shortcut's feature)
And now I'm curious where I made a mistake.
Bookmarklet's javascript was this = javascript:(function()%7Bwindow.open('https://[Your Server]/%23/home;url='%20+%20encodeURIComponent(window.location)%20+%20';audioOnly=false')%7D)()
Could anyone help me? Thanks.

**Comment by GlassedSilver** [comment]
I only remember Safari for iOS being a little bit of a princess with stuff like bookmarklets.

I haven't used it in forever and I think all iOS browsers are plagued by this afaik, since they all use Safari's rendering engine.

Only thing I remember is that if you wanna add bookmarklets to Safari for iOS you gotta make a bookmark for basically whatever, then edit the bookmark and delete the URL for that bookmark only to fill it with the entire string you copied for the bookmarklet. Then save.

That SHOULD do it.

**Comment by GlassedSilver** [comment]
Oh so like a PWA...

Well, all I know is that PWAs on iOS are in a REALLY sad state, I never bothered figuring out anymore after many frustrating attempts and stuff I add that way just loading into a browser tab anyways.

Can't really help you here I am afraid, but if any iOS users who still actually use iOS more actively than I do have any news on this front, especially maybe changes that may have come with iOS 15, you're more than welcome to fill in and suggest anything the project could add so this gets facilitated!

**Comment by u0a** [comment]
> Oh so like a PWA...
> 
> 
> 
> Well, all I know is that PWAs on iOS are in a REALLY sad state, I never bothered figuring out anymore after many frustrating attempts and stuff I add that way just loading into a browser tab anyways.
> 
> 
> 
> Can't really help you here I am afraid, but if any iOS users who still actually use iOS more actively than I do have any news on this front, especially maybe changes that may have come with iOS 15, you're more than welcome to fill in and suggest anything the project could add so this gets facilitated!

After a few trials and errors, I made a shortcut for iOS users. https://routinehub.co/shortcut/10283/ I hope more people can use it usefully.
Do I have to PR Readme.md or sth?

**Comment by GlassedSilver** [comment]
Thank you so much for your contribution to the project! Really fond that we're fostering such a wide community of users around here!

Already added a reference in the Wiki https://github.com/Tzahi12345/YoutubeDL-Material/wiki/iOS-Shortcuts-Workflow :)

You can also, if you wish, add a PR for the Readme so it counts as your contribution to the repo. ;)

Otherwise I don't mind doing it for you if you preferred. That PR would then be merged on the next regular round of code commits. (to not spam the docker builds when no code changes are made)
