### ISSUE TITLE
[BUG]bilibili's video won't play in Webui.

### ISSUE THREAD

**Issue by toniexly** [Tzahi12345/YoutubeDL-Material#495]
**Describe the bug**
mp4 dled from bilibil.com shows no thumbnail in webui and won't play.

**To Reproduce**
1. dl a video from https://www.bilibili.com/video/BV1h4411d7Yo/?spm_id_from=autoNext
2. go to webui and u'll see the problem

**Environment**
-  synology dsm7.0
- Docker nightly version

**Comment by GlassedSilver** [comment]
Which fork of ytdl are you using? yt-dlp, yt-dlc or classic yt-dl? At this point anything apart from yt-dlp is pretty hit or miss on many fronts.

**Comment by yllekz** [comment]
I've lately been having trouble getting this container to play any video. Thumbnails no longer load and most of the UI is just loading animations.

**Comment by GlassedSilver** [comment]
> I've lately been having trouble getting this container to play any video. Thumbnails no longer load and most of the UI is just loading animations.

Sounds a lot to me like your instance has grown quite a bit and that you haven't migrated to mongodb yet which scales much better than the default.

Load up a mongoDB container/host it anyway you wish and configure to use that in YTDL-M. YTDL-M will then copy over your db to there and start using that.

It makes a world of difference. This issue has been talked about in other issues before yours and I was one of the first to have a sizable db to notice this myself, so trust me I know how it looks like on your end. ;)

The change WILL help. Cheers. :)

**Comment by toniexly** [comment]
I'm using yt-dlp. i've tried all three in fact...

Glassed Silver ***@***.***> 于2021年12月16日周四 19:54写道：

**Comment by yllekz** [comment]
> > I've lately been having trouble getting this container to play any video. Thumbnails no longer load and most of the UI is just loading animations.
> 
> Sounds a lot to me like your instance has grown quite a bit and that you haven't migrated to mongodb yet which scales much better than the default.
> 
> Load up a mongoDB container/host it anyway you wish and configure to use that in YTDL-M. YTDL-M will then copy over your db to there and start using that.
> 
> It makes a world of difference. This issue has been talked about in other issues before yours and I was one of the first to have a sizable db to notice this myself, so trust me I know how it looks like on your end. ;)
> 
> The change WILL help. Cheers. :)

I am only using ytdlm for two small/medium sized playlists. It shouldn't require standing up a secondary database environment?

**Comment by zhangzhy2000** [comment]
Note the video format of bilibili. Most of them are flv, which was not supported.

**Comment by toniexly** [comment]
tried to set up a mongodb myself but the container keeps restarting..is there a step-by-step manual....

**Comment by GlassedSilver** [comment]
> Note the video format of bilibili. Most of them are flv, which was not supported. TRY: `ffprobe -i video.mp4` You'll see.

Yeah, flv is a b***...

I'm not sure if yt-dlp supports converting those with extra parameters, that MIGHT fix it, but I never tried that.

Basically, if I come across bilibili I download using my regular args and just suck it up that I may need to hit the filesystem to access them.

It's not elegant, but if anyone is keen on providing a player component change that can deal with those kinds of videos I will be the last to get in the way of the PR and the repo marrying. :D 

> tried to set up a mongodb myself but the container keeps restarting..is there a step-by-step manual....

Sorry for the late reply, but provided you have a mongodb instance set up (either in a docker or even bare-metal) then you need to put the connection string in **Settings > Database > MongoDB Connection String**

![Screenshot 2022-03-25 125507](https://user-images.githubusercontent.com/1912133/160116383-687c2936-b91c-4571-9b49-afd39e072a87.png)

1. _Change the IP and port_ to your mongoDB instance like shown above,
2. click `Test connection` string and if it succeeds...
3. hit `Save`
4. and `Transfer Local to DB`.
(mine says DB to Local because since I already set it up it offers me the other way around)

Best of luck and let me know if that helped you. And sorry again for the late reply.


> I am only using ytdlm for two small/medium sized playlists. It shouldn't require standing up a secondary database environment?

You'd be surprised how much better mongoDB-powered instances can run compared to the json file-based ones.

Mine hasn't been a small instance for a long time, but I can imagine how it's helping on smaller instances as well since I/O operations are greatly optimized.
