### ISSUE TITLE
[BUG] The Download button doesn't work

### ISSUE THREAD

**Issue by SeanChangX** [Tzahi12345/YoutubeDL-Material#501]
**Describe the bug**
1. If click the download button of videos or music, they all lead to download the file like ”example.mp3.json” or “example.mp4.json”

2. The mp3 can’t play on the safari browser of the iPad OS, but it works well on the image(**lastest**)

3. If using the yt-dlp downloader, it will show some void downloading item before downloading the video or music.

**Screenshots**
The safari browser on the iPad.
![image](https://user-images.githubusercontent.com/65809302/148005503-f493ffca-901b-4219-922f-5a96680f8015.jpeg)

The download list
![image](https://user-images.githubusercontent.com/65809302/148005526-18fd1e4a-496e-4513-b50b-eea33267d81b.jpeg)

**Environment**

Installed version: v4.2
Installation type: docker 
Docker tag: nightly
Build date: 2021-10-01

**Comment by SeanChangX** [comment]
After clicking the download button, the docker logs show this.
`
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined        
    at validateString (internal/validators.js:124:11)                                                   
    at Object.join (path.js:1148:7)                                                                     
    at collectInfo (/app/downloader.js:190:32)                                                          
    at runNextTicks (internal/process/task_queues.js:60:5)                                              
    at listOnTimeout (internal/timers.js:526:9)                                                         
    at processTimers (internal/timers.js:500:7) {                                                       
  code: 'ERR_INVALID_ARG_TYPE'                                                                          
} 
`

**Comment by SeanChangX** [comment]
I think problem(2) may cause by safari will block the auto-play videos.

**Comment by SeanChangX** [comment]
I find out the problem(3) happened after we clicked the download button, and it would create a void download item.

**Comment by GlassedSilver** [comment]
> I think problem(2) may cause by safari will block the auto-play videos. Maybe we can add an option in the setting to choose to open the auto-play or not.

Maybe I misunderstood, but don't you mean this setting?

`Settings > Extra > Allow autoplay`

**Comment by SeanChangX** [comment]
What I mean is something like this:
https://stackoverflow.com/questions/53434216/mp4-doesnt-play-after-initial-load-in-safari

https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari

**Comment by GlassedSilver** [comment]
Ooooh... I sadly don't have a (working) Mac anymore that I could give this a shot on, but honestly despite being a co-maintainer of the repo I'm really only capable of small fixups and merging PRs, providing support, etc...

I don't really think I can provide a fix here, but if anyone with the hardware and knowledge offers a PR I'll be happy to merge it.

Sorry that I can't be of any more help here, at least not now. :(

**Comment by SeanChangX** [comment]
Thanks, by the way. What about the problem(1)? I just update to the newest nightly vesion few days ago. But seems that still have the same problem. Unless I use the "cloud" download button let it redownload again.

**Comment by GlassedSilver** [comment]
Ahhhh I think I got it now. There's a floppy disk icon and the cloud icon. The cloud icon downloads the file correctly and the floppy disk icon downloads a small text file with the video extension.

Yeah that's a little odd. I'll reference this issue in the PR that submitted this change, maybe the friendly volunteer who provided the code can look into this. :)

#528

(I hope I'm not mixing stuff up or such, I'm tired as hell, so hopefully I even understood correctly what the issue is :D)

**Comment by Tzahi12345** [comment]
#554 Will fix this! See further details here: https://github.com/Tzahi12345/YoutubeDL-Material/pull/528#issuecomment-1106004143

**Comment by SeanChangX** [comment]
> Ooooh... I sadly don't have a (working) Mac anymore that I could give this a shot on, but honestly despite being a co-maintainer of the repo I'm really only capable of small fixups and merging PRs, providing support, etc...
> 
> 
> 
> I don't really think I can provide a fix here, but if anyone with the hardware and knowledge offers a PR I'll be happy to merge it.
> 
> 
> 
> Sorry that I can't be of any more help here, at least not now. :(

I finally found out the main reason why safari cannot play videos. It may cause by the downloaded videos’ coding not being supported by the safari on an iPad. It seems to cause by the yt-dlp because that was working well on the image(lastest). But like metube(https://github.com/alexta69/metube) same base on the yt-dlp, working quite well on iPad. I’m not sure what’s the difference between those videos from the yt-dlp, I will keep trying to figure out the problems. If there have something I should know, please tell me Thanks.

If somebody encounters this issue, you can use the app called nPlayer to play the videos.(URL or file)

**Comment by GlassedSilver** [comment]
Okay I did have a hunch after a while when I read about webm video format support on Apple and that on Mac it’s basically a thing (and a rather late addition at that!) whilst the iOS/iPad OS family is left to rot away without native support.

Either way, when switching to yt-dlp you will encounter a different behavior on how yt-dlp decides on which format is the best quality to download as per your passed arguments.

youtube-dl (the OG) used to heavily rely on bitrate and basically didn’t take into account that some codecs may be vastly better than others at the same bitrate or less even.

yt-dlp is aware of this reality and when passing the best args for format selection you will typically end up with HEVC, AV1, webm and VP9 formats, whilst iOS basically only supports HEVC of those iirc, but not VP9 and webm for sure. Maybe AV1 is supported as well, not sure atm.

When YT-DLM issues the download, it makes sure that the container of the resulting downloaded file will be mp4, typically that’s H.264, but also HEVC and yes, even webm codecs can be delivered in this container. (and possibly more, I don’t know these specs to the deepest level, but @Tzahi12345 did have some research about this at one point.)

mp4 as container makes sure it will stream more nicely, especially to Macs, but iOS/iPad OS are supper iffy (like so often).

Regardless, that’s the reason.

You can define a codec of your choice and even a preference list (for fallbacks and such) if you like, that way you’d be able to play these smoothly on any device, but I’ll clue you in that maybe you just let it be, because I guess long-term it’s best to take advantage of the best compressing HQ codecs and I think a rework of the player might include a transcoding feature as well. No promises though, because I wouldn’t be the one to write that functionality and I haven’t brought this up yet with @Tzahi12345. :P

**Comment by by275** [comment]
Codec was the problem. By replacing https://github.com/Tzahi12345/YoutubeDL-Material/blob/9c0a77cb6e4d3e36234ef58b9828b19a0404c528/backend/downloader.js#L416 with

```js
    let qualityPath = (is_audio && !options.skip_audio_args) ? ['-f', 'bestaudio'] : ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--merge-output-format', 'mp4'];
```

to specify types of video and audio, the issue can be resolved.
