### ISSUE TITLE
Progress-bar keeps in Indeterminate mode

### ISSUE THREAD

**Issue by mjpmme** [Tzahi12345/YoutubeDL-Material#51]
Hi, 
Thanks for doing this so awesome project. I'm not sure if it's an issue or something I misunderstand. Hopefully I make it here right.

I'm running it in docker. When a video is downloading, the progress bar doesn't show a percent complete, just keep looping from left to right. I tested it on Safari, Firefox and Chrome on macOS. I found it that this's called Indeterminate mode on this link: https://material.angular.io/components/progress-bar/overview. 

How can I set it to show Determinate mode?

**Comment by Tzahi12345** [comment]
Glad you're enjoying it! :)

The indeterminate progress bar is intentional, but it wasn't always that way. I decided to make it so many versions ago because I had a hard time actually determining the progress on the file.

Basically, the client periodically asked the server to check on the file size of the downloading mp3/mp4 and compare it to the expected file size. It worked in *most* cases, but sometimes the file would split into parts or be in an entirely different format before being converted. So I gave up on the half-solution, and haven't revisited it since then.

But I was thinking about this recently, and it is something I'd like to implement sometime soon, as it would provide essential information to users. I'm sure there will be a lot of edge cases, so maybe have the indeterminate mode be a fallback in case the server can't determine the actual progress.

I'll put this up as a feature to add for the next update, v4.0. Still deciding which features I want for that update, so it might be some time until it gets implemented. Btw, you're in the right place for suggestions/questions, so feel free to open up any more issues if you encounter anything else or want to recommend a feature. They are always appreciated!

**Comment by mjpmme** [comment]
Great explanation for me. Thank you.

**Comment by nebula-it** [comment]
Just to add on to this, possible for progress bar to show up on other devices? E.g I start the download from my phone and opening up ytdl on my PC currently does not show currently downloading files/progress bar. It would be ideal if its possible to check from other devices as well.
Cheers

**Comment by Tzahi12345** [comment]
>possible for progress bar to show up on other devices?

This is a good idea, but it will require a refactor of the way current downloads are managed. Right now it's all done in the UI, but for other devices to get that information the backend needs to be doing most of the legwork. This would be a great change actually, as it would give the backend more freedom on managing active downloads (making cancelling downloads actually possible, developing a possible queuing system)

I'll include this in the next update, thanks for the suggestion!

**Comment by Tzahi12345** [comment]
Just leaving a comment to let you know this has been implemented download progress bars! It isn't enabled for audio files as the download speeds appeared significantly slower, but I will investigate this more and may make the downloading method configurable. Thanks @mjpmme for the suggestion!

@nebula-it your idea for viewing downloads across other devices is implemented as well. There's a new downloads manager that has been added where you can view all of this. It isn't organized in the prettiest way now so that will be worked on until it gets released in 4.0. Thank you for recommending this feature!

You can view the relevant [pull request here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/57) for more info and a sneak peek of the downloads manager.

**Comment by nebula-it** [comment]
That looks great!. Good job @Tzahi12345 . 
Looking forward to further enhancements with audio and playlist downloads. 
Cheers

**Comment by mjpmme** [comment]
Thanks @Tzahi12345 that’s awesome!
