### ISSUE TITLE
[BUG] Videos are not showing on the UI

### ISSUE THREAD

**Issue by jeffward01** [Tzahi12345/YoutubeDL-Material#520]
**Describe the bug**
I have ran the download script overnight, and many videos have downloaded (yay) - However, the videos do not show on the UI.  See screenshot.

I run this in Unraid and docker.. so perhaps the video files are on my cache drive and it does not appear because the application does not 'see' the Cache files? It will be odd, because all the other programs do see the cache files. 

I just wanted to report this bug
 

**Expected behavior**
All complete downloads should show on UI

**Screenshots**
 
![youtube-dl-UI](https://user-images.githubusercontent.com/12589359/153938676-3969299a-52a8-48df-af0a-2aca850e2f5b.png)

**My log file**
````txt
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T19:32:01.353Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T19:37:01.755Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T19:42:01.755Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T19:47:01.936Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T19:52:01.894Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T19:57:02.014Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T20:02:01.986Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
2022-02-14T20:07:01.875Z ERROR: WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
````

**Comment by GlassedSilver** [comment]
This is a known issue, the UI will sometimes take a little bit of time to actually show new downloads in the main view.

Oddly the Subscriptions pages usually update much faster (at least in my experience), so if you have those coming in quick that's something I can observe as well.

Sometimes restarting the container fixes it, but not always right away.

Also, if I can tell correctly you're using the latest stable release of YoutubeDL-Material.

I'd STRONGLY advise you switch to the nightly build!

After that make sure you run YTDL-M with a mongoDB backend. [Here are the unRAID-specific instructions.](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/unRAID#mongodb-database-setup)

**Comment by GlassedSilver** [comment]
Another thing I want to point out is that sometimes new downloads may get crammed away on further pages, because by default the items are sorted by upload date.

Say you download a video that got uploaded at the source (i.e. Youtube or something) 3 weeks ago and your page 1 is full of videos from the past few days. (for example you may see current videos from your subscriptions)

The video will not move ahead of the list, because it's too old at the source.

You can also sort by download date which would shows videos in the order they downloaded to your YoutubeDL-Material instance.

This may not be relevant for your current setup with only 2 videos showing to begin with, but it's certainly something that may help those who have well populated instances and want to check on their progress in the order the media items are ingressed. :)

![Screenshot 2022-03-26 174724](https://user-images.githubusercontent.com/1912133/160249360-e07e14be-046c-42fe-b1ca-e0fbed8e254e.png)

**Comment by GlassedSilver** [comment]
I'll close this issue now, because on recent releases of nightly and using the MongoDB backend I noticed subscriptions appearing in a timely fashion. You can manually trigger a "refresh" of the home page view of the listed videos to show the uploads in an updated order like so:

**Select to sort by downloaded date and then hit the up/down arrow twice. (basically cycle it once)**

![Screenshot 2022-04-17 133252](https://user-images.githubusercontent.com/1912133/163712541-bddf2e0c-4dc5-4511-8e33-82183206f4c7.png)

This view setting shows me the latest stuff sorted in order of ingress rather than upload date at the source (e.g. YT's upload date) :)

If this issue still persists on the latest nightly using the MongoDB backend feel free to comment, and I'll reopen the issue. :)
