### ISSUE TITLE
[BUG] Synology Docker Image problem

### ISSUE THREAD

**Issue by herotm** [Tzahi12345/YoutubeDL-Material#525]
I downloaded the nightly image on Synology Docker resgistry, I have everything configured web UI works fine, the Synology Firewall allows all docker ips. When I download a Youtube URL this is the error I get

Error while retrieving info on video with URL https://www.youtube.com/watch?v=MZ6CqqdPRLQ with the following message: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl -o audio/%(title)s.%(ext)s --write-info-json --print-json --audio-quality 0 -x --audio-format mp3 --write-thumbnail --dump-json http://www.youtube.com/watch?v=MZ6CqqdPRLQ

WARNING: Unable to download webpage: <urlopen error [Errno 0] Error>
ERROR: Unable to download API page: hostname u'www.youtube.com' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com' (caused by CertificateError("hostname u'www.youtube.com' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by GlassedSilver** [comment]
I don't have a Synology system to check this out on, but this seems really odd. I don't think that's in the realm of YoutubeDL-Material's code.

Does the Synology docker repo have its own support forum? I'd try asking there instead, because I have never seen this error before on my end. (at least not that I'd know)

Personally I run YTDL-M as a docker in unRAID.

Maybe try the latest nightly? (I've fixed some backend dependencies over the last few days and we received some helpful PRs that I merged)

Keep me updated, I'd love if you could come to enjoy YoutubeDL-Material as well! :)

**Comment by herotm** [comment]
This is a problem with my internal adguard issue that caused dns issue with ssl encryption. Closing

**Comment by GlassedSilver** [comment]
Thanks for the follow up. Both because it helps us focus on the actual on-going issues as well as for helping others troubleshoot when they spot the same problem! :)

Have a nice rest of your weekend!
