### ISSUE TITLE
--write-info-json generates file, but I have no permission to open it unlike the video and separately stored thumbnail

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#53]
Issue is as title says, not sure how this is happening. Maybe the json-writing process is run by under a different user ID?

I also stopped the container to make sure that youtubedl-material isn't trying to access and lock the file... No game.

**Comment by Tzahi12345** [comment]
Hm, could you run `ls -l` and get the permissions on the file? I've encountered issues where videos get locked up, but the JSON file being unreadable even after closing the app seems like it's a permissions issue.

If it is a permissions issue, a possible fix is making sure the JSON file is open to all reads/writes (777) after a video downloads. Just a thought, let me know if `ls -l` shows anything interesting.

**Comment by GlassedSilver** [comment]
`ls -l` did indeed reveal something interesting.

video and thumbnail files:
`-rw-r--r--    1 root     root`

json:
`-rw-------    1 root     root`

Guess there's the problem. :)

**Comment by Tzahi12345** [comment]
Ok, that is quite interesting... I just checked my JSON files and saw the same thing. Couldn't find any related issues for youtube-dl, maybe they want it that way for whatever reason.

I've added some code in so that when the JSON files get created, it has the same permissions as the other files in the directory. Here's the [relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/2408184cc7ed3be4030de79b6eed52ad579b63e0), just note some minor changes were made later to avoid compatibility issues. You can test this out if you switch to the `nightly` tag on Docker (just set up automatic builds!), otherwise the next update will have it included. In the meantime, it should be possible to access the files with sudo.

Anyways, that should fix the bug. Let me know if anything else pops up!
