### ISSUE TITLE
[HELP] Unable to use YT-DLP

### ISSUE THREAD

**Issue by projx** [Tzahi12345/YoutubeDL-Material#553]
**Describe the bug**
When switching the dowloader to YT-DLP on a new install on the YTDL-Material container, I get the following error:

```
2022-04-20T22:02:11.696Z ERROR: Failed to check yt-dlp version for an update.
Error: listen EACCES: permission denied 0.0.0.0:443
    at Server.setupListenHandle [as _listen2] (node:net:1363:21)
    at listenInCluster (node:net:1428:12)
    at Server.listen (node:net:1516:7)
    at Function.listen (/app/node_modules/express/lib/application.js:618:24)
    at startServer (/app/app.js:251:9)
    at loadConfig (/app/app.js:574:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async setAndLoadConfig (/app/app.js:523:5) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 443
}
2022-04-20T22:02:11: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
```

**To Reproduce**
1) Do a refresh installation of the YTDL-Material docker image, using the night build (Note, I'm experiencing the same issue with both Docker and K3S)
2) Goto settings, change the Downloader agent from YTDL, to YT-DLP.
3) Restart the container
4) The log above appears in the output and the container goes into a crash loop

**Expected behavior**
The download agent should either already be pre-installed on the Image, or it should successfully download it, and then continue to load.

**Screenshots**

**Environment**
- YoutubeDL-Material version
- Docker tag: Nightly

**Comment by Tzahi12345** [comment]
This looks like a network issue on your end, I can download it just fine. Can you share your docker-compose?

**Comment by GlassedSilver** [comment]
This is a file permission error.

Try repulling the latest nightly and see if that fixes it. (note: we haven't changed anything in the docker image, but maybe something messed up the ytdl binary permission)

The docker compose file would definitely be something I'd love to see as well, maybe this can clue us in.

Did you set different `PUID`/`PGID`?

**Comment by GlassedSilver** [comment]
A new nightly is releasing in ~1h, please try with that build and report back :)

**Comment by JoostHazelzet** [comment]
I believe this is a user error in setting the port configuration. I had exactly the same error, and the issue is related to 'listen EACCES: permission denied 0.0.0.0:443' in the log. 
To resolve it, I opened the /appdata/default.json and changed "port": "443" back to to "port": "17442" (default value). 
My 2 cents, the user can change the port in the web frontend under settings - main to 443. Next the user can restart the the application by 'Restart server' in Settings - Advanced. But if the 443 port is already used by another service then it throws this particular error and as a consequence the web frontend is no longer started. And only way to restore is going to /appdata/default.json.
