### ISSUE TITLE
Allow for URL base path in settings

### ISSUE THREAD

**Issue by Kruhlmann** [Tzahi12345/YoutubeDL-Material#56]
I wanted to host the software on a subpath on my domain, but was unable to do so, and had to resort to creating a new subdomain for it.

Allowing a subpath to be specified in the configuration would be very helpful.

**Comment by Tzahi12345** [comment]
Have you checked out the [reverse proxy setup](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Reverse-Proxy-Setup) page? You can use nginx or apache2 to channel all requests through your web server, not sure if you're doing this already. You can set a subpath using the appropriate configuration. Some more details on your setup would be helpful for figuring out how to get it working on the subpath.

Since the last update, the frontend url setting isn't actually used anymore. The server just exposes the port specified, and because your subdomain likely points to the same place as the root domain, it send you to the right place.

It would be a nice feature to have, but I'm not sure if there's a way to allow for subpaths without interfering with web servers like nginx or apache2.

**Comment by Kruhlmann** [comment]
You're right I missed this part here in the configuration:

```
location ~/ytdl(.*)$ {
	rewrite /ytdl/(.*) /  break;
	proxy_pass http://example.com:8998;
}
```

I didn't realize it was possible to route using paths like this. My bad :+1:

**Comment by Tzahi12345** [comment]
Cool! Glad you got it working.

**Comment by hjhee** [comment]
Hi, I'd like to point out a problem when reverse forwarding the `/api` path using another reverse proxy server *traefik*. When its dashboard is enabled, it requires that both `/api` and `/dashboard` be forwarded to its internal service. So it means the `/api` could not be forwarded to youtube-dl-material.

`traefik` is a popularly used reverse proxy server that handles routing for docker images without manual configuration. It would be great if the wiki also provides instructuion.

**Comment by qlonik** [comment]
Hey. I encountered the same problem with traefik. It seems that the path for api endpoint is hard-coded via [this line](https://github.com/Tzahi12345/YoutubeDL-Material/blob/de154a9c3eaf55e037cc42d0fbd72a78afc05584/src/app/posts.services.ts#L64). If it could be configured somehow so we can add extra subpath between location origin and `/api/`, I think it would solve our issues.

**Comment by Tzahi12345** [comment]
@qlonik The main issue with that the frontend would be unaware of the new path. The backend would need an API subpath just for the config, and then before any other requests get send out, the frontend would have to retrieve that. Not an impossible solution, but perhaps it would be better to replace `/api` with something that won't collide with other apps, like `/ytdl_api`. It's a bit ugly and would break a lot of people's reverse proxy setup, but so would the first solution too.

If the reverse proxy workaround works, I'm *inclined* so say that's the official way to go, but I could definitely be convinced otherwise as traefik isn't some obscure proxy service.

**Comment by samcro1967** [comment]
Anyone have any luck getting this to work in caddy without a base url?

**Comment by kzaoaai** [comment]
> @qlonik The main issue with that the frontend would be unaware of the new path. The backend would need an API subpath just for the config, and then before any other requests get send out, the frontend would have to retrieve that. Not an impossible solution, but perhaps it would be better to replace `/api` with something that won't collide with other apps, like `/ytdl_api`. It's a bit ugly and would break a lot of people's reverse proxy setup, but so would the first solution too.
> 
> If the reverse proxy workaround works, I'm _inclined_ so say that's the official way to go, but I could definitely be convinced otherwise as traefik isn't some obscure proxy service.

Was this pursued? replacing api with something more specific? I have the main issue as another container (Organizrr) uses /api/ on the main page.

**Comment by Tzahi12345** [comment]
@kzaoaai 

My main hesitation here is that there's a decent chunk of people who have reverse proxies setup with the `/api/` route. I guess that's a bad reason to not change it but if I can avoid having a breaking change I'd prefer that. But maybe it's not possible.

Let's do a poll of sorts, then. If this comment gets 5 thumbs up without a violent reaction I'll change it. Otherwise I'll keep it as it is.

**Comment by kzaoaai** [comment]
how about maybe an environment variable that defaults to /api/ ? That way, people who have a conflicting app like me can change it, while others will keep the default /api/.

I personally have no clue how to implement it, just a thought.

**Comment by kzaoaai** [comment]
@Tzahi12345 that should do it. I'd be glad to test your proposed fix. Thanks!

Sidenote: I've seen a couple other people post in the issues about the api, and i'm sure most just implemented a subdomain instead. That works only if the auth module api for organizr is disabled for the subdomain.

**Comment by GlassedSilver** [comment]
`/ytdl_config/` first call to check for which is set:
`/ytdl_api/` or `/api/`

That way you have less semantic redundancy.
