### ISSUE TITLE
[BUG] Every Downloads Are Failing

### ISSUE THREAD

**Issue by guillaumesoucy94** [Tzahi12345/YoutubeDL-Material#605]
Hello, 

When trying to download a video, YoutubeDL-Material WebGUI is showing “Download Fail” and in the logs I have this: ERROR: ERROR:   Stream #1:0 -> #0:1 (copy)

How to make it work?

Regards, 

Guillaume

###

**Describe the bug**

When trying to download a video, YoutubeDL-Material WebGUI is showing “Download Fail” and in the logs I have this: ERROR: ERROR:   Stream #1:0 -> #0:1 (copy)

**To Reproduce**
1. Go to 'Main page'.
2. Paste any YouTube link.
3. Wait for it download.
4. It throw the error

**Expected behavior**
The video get downloaded without problems.

**Screenshots**

**Environment**
- YoutubeDL-Material version: 4.2
- Docker tag: <tag> (optional)

Ideally you'd copy the info as presented on the "About" dialogue
in YoutubeDL-Material.
(for that, click on the three dots on the top right and then
check "installation details". On later versions of YoutubeDL-
Material you will find pretty much all the crucial information
here that we need in most cases!)

**Additional context**
This is the first link that I'd tried: https://www.youtube.com/watch?v=lKDSt6SAeuM

Please note that nothing can be downloaded without an error in the WebGUI

**Comment by GlassedSilver** [comment]
Please provide the information requested in the issue template.

At the very least tell us which docker tag you’re on (`nightly` or `latest`? Latest is unsupported atm)

And when you pulled the docker if it‘s `nightly`.

**Comment by guillaumesoucy94** [comment]
Hello, 

I did not use the Docker install way, I'd instead choose the instructions under Installing [https://github.com/Tzahi12345/YoutubeDL-Material#installing](url)

Can I make it work without the use of Docker? Or if I must use the Docker way?

Regards,

Guillaume

**Comment by GlassedSilver** [comment]
No you don't have to use docker, it's just recommended to use it.

If you want to stand up your own instance without docker I'd suggest you don't get the release though, since that's very outdated.

Instead, for simplicity's sake wait for the soon releasing version 4.3! 👍

That'll get bundled up in a nice release that'll be easy to deploy.

If you want to install asap, you'll have to build it yourself though, that process is described here: https://github.com/Tzahi12345/YoutubeDL-Material#build-it-yourself

You'll need node.js version 12 and for that. We also make use of the angular framework.

If that sounds like too much hassle to you, that's fine, as I said the next version is due to release very soon, just note that [the release you probably downloaded](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v4.2) following the instructions here (https://github.com/Tzahi12345/YoutubeDL-Material#installing) is very outdated. So any issues you encounter in that version we cannot take into consideration anymore, since 4.3 is our focus.
