### ISSUE TITLE
Download selected file to client

### ISSUE THREAD

**Issue by noja11** [Tzahi12345/YoutubeDL-Material#61]
Is there a way to download a file from the site to my local client? I'm thinking this might be most useful once multi-user mode is finished up, but still helpful in any case.

Essentially, once someone is on the site and they are browsing through the Video Files - they click on the video and then click to download directly to their device.  This is especially useful when the ytdl path is saving files to a shared drive that the user doesn't have easy access to.  

If that function is already there, fantastic! Otherwise, I think it would be very useful.

Thanks

**Comment by Tzahi12345** [comment]
It should be! I think I discovered a bug that prevented this from working, in the Docker `nightly` build it should be fixed, though in v3.6 you can see the "save" button present in the video player.

Should look something like this
<img src="https://i.imgur.com/wYoFrHJ.png"  width="700">

Clicking that will download the video. Unfortunately (as I discovered yesterday), this may be broken on v3.6, but the Docker `nightly` builds have the fix included. If it's broken on your end, you can download the videos using Chrome's default video/audio player, but it isn't as intuitive.

I've already converted the save button functionality to support multi-user mode, so that feature is good to go for the next update.

If you don't like the video player, you can also enable download-only mode in the *Extra* tab in the settings. If you click on a file in the file manager, it will simply download the file locally. 

If you don't like the file manager either, you can disable that, too, and all files downloaded will just get downloaded directly to the client after the download completes, with the file getting auto-deleted server-side once that is done.

Anyways, hope this helps!

**Comment by noja11** [comment]
Ahh!  I figured it would be that save button, but every time I used it, nothing happened.  Glad to hear you're way ahead of me. I'll wait for it to make its way into the stable branches.  

Also, multi-user mode is very much supported by my wife, thanks so much for all your hard work!

**Comment by Tzahi12345** [comment]
Haha appreciate it :) ETA is 2 weeks or so, so it's coming soon!

**Comment by Tzahi12345** [comment]
@noja11 Just wanted to let you know v4.0 is out with multi-user mode of course included! You can view the [release notes here](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v4.0). Happy downloading!

**Comment by noja11** [comment]
@Tzahi12345 thanks so much for all the hard work! Multi-user is very much appreciated.  Looks good.
