### ISSUE TITLE
[FEATURE] Rescan Playlist

### ISSUE THREAD

**Issue by Hussienfahmy** [Tzahi12345/YoutubeDL-Material#623]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A rescan button to the playlist to download any missing video from it (for example any videos will uploaded in the future)

**Comment by GlassedSilver** [comment]
How did you add the playlist to YTDL-M?

If you subscribed it future additions to it should automatically be added.

**Comment by Hussienfahmy** [comment]
Yes I subscribed to it, I was searching for an alternative supporting this feature. That should be highlighted to attract more user.
Thanks sir for clarifying

**Comment by GlassedSilver** [comment]
> Yes I subscribed to it, I was searching for an alternative supporting this feature. That should be highlighted to attract more user. Thanks sir for clarifying

Well if you subscribe to a playlist it will be checked for new entries, I think that should be pretty clear since the whole purpose of subscriptions is to automatically ingres new content.

No problem though,  glad we could help you out and I hope you enjoy the application a lot still going forward!
