### ISSUE TITLE
Download queue management and retires

### ISSUE THREAD

**Issue by chimlm** [Tzahi12345/YoutubeDL-Material#65]
Is there a way/option to set the maximum concurrent downloads?

I added a channel with over 100 videos. I can see there are 10 to 12 youtube-dl processes inside the docker. Looking at the process ids some appear to be stale. The memory usage of the container gradually climbs to around 500MB. Is it possible to control how many videos can be download at the same time? As this is a background downloader, it's okay to have as low as one active video download to avoid OOS situation on the server and not to overload the Internet line.

There are some videos that only the beginning few minutes are playable, the rest of them are choppy or even unwatchable. Seems like that some partitions of the videos are not downloaded correctly. Is there an option to report such error and control the number of retries for failed segment?

**Comment by Tzahi12345** [comment]
>Is there a way/option to set the maximum concurrent downloads?

There isn't currently, but I've been slowly building towards this feature. In the next update, downloads will be tracked by the server, and there will be a downloads manager where you can see the progress of each download and any errors if they occur. This is the first iteration, so it only works for downloads from the home page (not subscriptions). There's also no queue yet. It'll require a refactor of the current system to support that, but about half of the work has already been done.

>As this is a background downloader, it's okay to have as low as one active video download to avoid OOS situation on the server and not to overload the Internet line.

You're absolutely right. While you can control how often subscriptions get checked, there's no download-limiter which can cause issues, I've gotten these 429 errors from youtube-dl which is basically YouTube blocking your IP from downloading videos for a day because of the volume of traffic.

I want to end up with a system that's easy to control. Allowing people to set the `--sleep-interval SECONDS` parameter comes to mind. When used with a channel/playlist it delays each video downloaded by the given amount. That, combined with a visible (and maybe editable?) queue where you can set maximum concurrent downloads (channels/playlists would be considered 1 download).

>There are some videos that only the beginning few minutes are playable, the rest of them are choppy or even unwatchable. Seems like that some partitions of the videos are not downloaded correctly. Is there an option to report such error and control the number of retries for failed segment?

There's a *delete and re-download* button. Just click on the 3 dots on the top-right of the video card, the option should show. I haven't experienced your problem, however, so that might be a bug to look into. Let me know if you see any patterns or errors regarding the file corruption.

**Comment by chimlm** [comment]
I noticed that for playlist/channel download. The video that appear corrupted will have a .mp4 file and a smaller .mp4.f140 file saved to the folder. The data in .f140 file is MP4 video data. It looks like it's a segment of video data that didn't get merged into the final MP4.

**Comment by Tzahi12345** [comment]
Hmm that sounds like the downloads are just getting cut off at some point, not sure if it's youtube-dl or YouTube doing it. Is it usually for large playlists/channels or are small ones affected as well? I'm wondering if it's the many concurrent downloads that's causing them to fail.

**Comment by chimlm** [comment]
It happened to a playlist with 18 videos so the list doesn't need to be very big to trigger this situation. Is it possible to check for those .f140 files as a hint of failure?

**Comment by Tzahi12345** [comment]
That definitely sounds possible. Maybe in the upgraded downloads system the server can periodically check the current downloads for any signs of errors (such as any files with the string `.f*.mp*` in them).

Hopefully redownloading the videos can serve as a workaround until this better downloads management system gets implemented.

**Comment by Tzahi12345** [comment]
Closing this issue as I'm consolidating related feature requests to #411 and #397!
