### ISSUE TITLE
Toggle for generation of JSON file

### ISSUE THREAD

**Issue by munimisu** [Tzahi12345/YoutubeDL-Material#71]
Its always generating a JSON file for each downloaded video. It would be really great to have a toggle to have the json generation on/off. Thanks

**Comment by Tzahi12345** [comment]
Good idea! This should be possible. The reason why they got generated in the first place is so the vital video info gets stored *somewhere* (things like file name, file size, etc.). Since then, I've started storing the video info in the server's database, which is a much better solution and it doesn't require those pesky JSON files.

Subscriptions do still need the JSON file. This is because subscriptions use the old system of finding videos and their info (the server searches through the directory and finds videos that have JSON files as well). I am planning on refactoring it so that subscription videos use the new system which doesn't require JSON files, but I'm not there yet. Once that is done, it *should* be possible to toggle it off without issue.
