### ISSUE TITLE
Can player remember audio volume setting?

### ISSUE THREAD

**Issue by chimlm** [Tzahi12345/YoutubeDL-Material#74]
The play back volume is at maximum for every newly opened file. If this can be remembered per browser would be nice. (using a cookie?)

**Comment by Tzahi12345** [comment]
This looks possible, would probably be quite easy to implement. Cookies would be great for this. Thanks for the suggestion!

**Comment by Tzahi12345** [comment]
This functionality has been added in the [latest PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/149), thanks for the suggestion!

**Comment by chimlm** [comment]
For some reason the volume memory is not working properly. It will just revert to 100% after going back to home page. /#/home

I am using the new Edge browser based on Chromemium.

In the Local Storage there's a new key "player_volume". When I change the player's volume the value will change to a fraction. But when I press back button on the GUI (not the browser's "back" button), the value reset to 1.

**Comment by Tzahi12345** [comment]
Wow, good find. Basically, after navigating home, the media player would derender and the volume setting presumably went back to its default. This was a problem as the volume *check* was still running in the background, detected the change in volume, and reset the cookie back to 1.

The fix here was to stop the volume check from occurring outside of the player component. When the player component gets destroyed, the volume check also gets destroyed. And voila, the problem is gone!

[Here's the commit.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/14bd82c5081a36c3ce93d6c965499dc251dd880c#diff-a7eb8c84a068b9c9c23a3a988dc39cf1) Update to the latest nightly and you'll have the patch included. Thanks for the report and helpful debugging! Saved me some precious time there :)
