### ISSUE TITLE
[FEATURE] download to individual directory

### ISSUE THREAD

**Issue by droopified** [Tzahi12345/YoutubeDL-Material#759]
similar to jdownloader, is it possible to put each download in its own directory with the title as the name?

**Comment by srwareham** [comment]
You can currently do this using the output template feature. Go to Settings->Downloader and modify the `Default file output` field. You can use the templating formatting defined [here](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template). If you include a "/" in the template, it will both create the parent folder you want and nest the child files. As an example, here's the template I use:

`%(webpage_url_domain)s-%(id)s/-%(webpage_url_domain)s-%(id)s.%(ext)s`

The format terms are repeated in this case because I want the parent directory and the child files to all share the same naming.
