### ISSUE TITLE
FEATURE REQUEST: after pasting in a URL, allow CR same as clicking Download

### ISSUE THREAD

**Issue by bcurran3** [Tzahi12345/YoutubeDL-Material#77]
Disclosure: This is a "me thing."

Whenever I paste in a URL, "muscle memory" kicks in and I automatically hit enter. I'm then "greeted" by "Please enter a valid URL!" 

It would be great if hitting enter after pasting in a URL that it would start the download without having to click the Download button. :)

Pretty please!

![image](https://user-images.githubusercontent.com/14026600/81466112-dba52d00-9183-11ea-909d-c6176fc6d950.png)

**Comment by Tzahi12345** [comment]
Nice catch, I've gone ahead and updated this so it's possible. Thanks for the find!

You can view the relevant [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/ecc2737a050a7bb7ef4068587e62ad9e9fd588d7). If you switch to the `nightly` tag on the Docker image, you should be able to do this immediately. Otherwise, you can wait for the next minor patch which will come in a couple days, ish.

**Comment by bcurran3** [comment]
Danka shoen Isaac!
