### ISSUE TITLE
Cannot download Twitch videos

### ISSUE THREAD

**Issue by suckerfish** [Tzahi12345/YoutubeDL-Material#81]
It grabs a tiny portion of it. 42kb or something. Gets a thumbnail generated and the title, but that's about it. 

I know youtube-dl can do Twitch videos normally on command line. I am not sure if YoutubeDL-Material is intended to be able to download any and all videos that the CLI command can download. 

Example video URL is here: https://www.twitch.tv/videos/613057832

**Comment by Tzahi12345** [comment]
It might just be the sheer file size on that twitch video (~25GB). I tried with this smaller clip and it downloaded just fine:

    https://www.twitch.tv/blacknerdgames/clip/ScaryBashfulWombatPeteZarollTie?filter=clips&range=7d&sort=time

Is this happening for all your twitch videos, or just the large ones?

**Comment by suckerfish** [comment]
Honestly I haven't tried others yet. FYI it doesn't pretend like it's downloading or 'in progress' over a period of time at all. Seems to give up pretty quickly. I will do more testing and report back.

**Comment by suckerfish** [comment]
Looks like just the large ones. I haven't figured out the cut-off point yet, but that first video was very long at like 6+ hours. I tried one that was only 90 min(?) or so and it also didn't work. A 30 second clip worked fine, though. 

Do you know why it would be having trouble with larger downloads like this?

**Comment by Tzahi12345** [comment]
I think I know why this is happening. The main method of downloading is to create a stream of the content and download the video through the stream. For some reason, large files cause the stream to screw up (this part I'm unsure of why).

Anyways, there's a backup method which does it the standard youtube-dl way (playlists also use this method). You lose features like a progress bar, but I tested it with the Twitch video you sent me and it works just fine (I cut the download off at 2GB to save myself the space, but I assume it works). You can see the relevant [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/c6553d99c6e0e127a4246eaf14e1d85fb1db33ce). If you're on the Docker, you can use the `nightly` tag to get the fix, otherwise you can wait until the next patch.

Thanks for the bug report, let me know if anything else comes up!

**Comment by suckerfish** [comment]
Hello - I just tried this again and it did seem to download the video successfully, but the GUI gave me an error after about maybe 20 seconds of waiting and I didn't realize it actually worked until I was browsing my videos the next day and came across it. 

Would it be possible to 'cover' for this in some way by having a message come up like "This is a very large file. It will download in the background. Check back later"? I guess just something other than an error message. Would throw people off otherwise :)

**Comment by Tzahi12345** [comment]
Did you get a specific error from the server or GUI that you can share? If it's specific enough to this problem, adding a simple error message saying `Error! Download failed, make sure the file size isn't enormous` or something like that would be pretty simple.

**Comment by suckerfish** [comment]
It's the 'Download Failed!' toast message that appears for a few seconds at the bottom of the screen. I just tried a 4gb twitch video and after roughly 2 minutes it appeared. 

Just to be clear, the video downloads fine. 16.7GB last one I just tried. The only issue is that the UI sorta 'gives up' about 2 minutes in because it thinks it failed. It continues downloading in the background just without any feedback. That's the only part I wanted to point out.
