### ISSUE TITLE
Some suggestions 

### ISSUE THREAD

**Issue by ibrahimk157** [Tzahi12345/YoutubeDL-Material#83]
Hello there!

First and foremost, great job on the recent updates! You’ve been absolutely killing it!

I’ve got a few suggestions which I personally think would make YoutubeDL-Material better:

1) Instead of having the downloaded file name something like “Youtube Downloader-12.mp3”, why not make it the same as the video title. Let’s say you’re downloading a video labeled “Cats”, then the downloaded file would be named “Cats.mp3”

2) Real time progress in percentage: would be great if we get a real time percentage progress as soon as we hit download. Would be much more informative!

3) Direct link download: I’ve seen several youtube downloading sites that point the browser to the direct link of the video which makes it download it. This would be great for larger videos instead of waiting for youtubedl to download it on the server first (which will take forever!). Not fully sure how this is achieved though.

Thanks!

**Comment by Tzahi12345** [comment]
Thanks for the suggestions! I'll go through one:

1. Right now, the default file name for local downloads (meaning when you save it to your computer) already uses the video title. Are you seeing a difference here between the file name on the server and the downloaded file name? It should be the same.

2. Good point, I have it set up so the progress bar only shows the real value when 15% of the video is downloaded (might be more, I forget). I'll change it to 1% or so, which will make it appear almost instantly. 

Besides that, the progress doesn't include a percent value, you kind of have to eyeball to know how far it's gone. I'll make it so the real percentage is shown, as well as time remaining if I get to that.

3. I like this idea, but I'm also not sure how to implement it exactly. Most downloads (not playlists and subscriptions) actually use the method you described, where we get a stream link to the video and download it that way. It shouldn't be too difficult to provide this link to the user, or better yet, add a setting so that no videos are actually downloaded (a global streaming-only mode perhaps).

An issue that needs to be resolved is that sometimes these stream links change, so it might require periodic checking to make sure it isn't stale.

Streaming-only mode is supported right now for subscriptions (it's an option when you subscribe). Let me know if this is how you'd like it to be setup for all downloads (optionally of course).

Anyways, thanks for the suggestions and the kind words! They are very much appreciated :)

**Comment by ibrahimk157** [comment]
> Thanks for the suggestions! I'll go through one by one:
> 
> 1. Right now, the default file name for local downloads (meaning when you save it to your computer) already uses the video title. Are you seeing a difference here between the file name on the server and the downloaded file name? It should be the same.
> 2. Good point, I have it set up so the progress bar only shows the real value when 15% of the video is downloaded (might be more, I forget). I'll change it to 1% or so, which will make it appear almost instantly.
> 
> Besides that, the progress doesn't include a percent value, you kind of have to eyeball to know how far it's gone. I'll make it so the real percentage is shown, as well as time remaining if I get to that.
> 
> 1. I like this idea, but I'm also not sure how to implement it exactly. Most downloads (not playlists and subscriptions) actually use the method you described, where we get a stream link to the video and download it that way. It shouldn't be too difficult to provide this link to the user, or better yet, add a setting so that no videos are actually downloaded (a global streaming-only mode perhaps).
> 
> An issue that needs to be resolved is that sometimes these stream links change, so it might require periodic checking to make sure it isn't stale.
> 
> Streaming-only mode is supported right now for subscriptions (it's an option when you subscribe). Let me know if this is how you'd like it to be setup for all downloads (optionally of course).
> 
> Anyways, thanks for the suggestions and the kind words! They are very much appreciated :)

For 

1) I use it on mobile... and the file name used to appear as youtubedl-material.mp3 when I was in version 3.5... when I updated to 4.0 (I skipped the other versions since I never got the time to frequently update), the file name was as I described above. HOWEVER, when clicking on an .mp3, the video title and author/channel name does show up... just not as the file name.

2) On mobile, I don’t get any percentage even after 15% is done... guess you’re talking about it for PC

3) I was thinking it would use the regular way for smaller file sizes/smaller videos, and if the size exceeds a certain value (maybe configurable in settings?), it would use the direct link method. However, not entirely sure if this will work while downloading on mobile (it does work when using other sites, but not all of them... not sure what each is doing differently)

Thank you!

**Comment by yllekz** [comment]
Is Streaming Only mode supported with playlists? I see it's an option in the settings but when I tick it and click "save" it never remembers it.

**Comment by GlassedSilver** [comment]
Going through old issues, cleaning them up, getting back to folks, etc... 🎶🎵 :)

1. I don't quite remember if I've ever seen YTDL-M download to a filename that isn't the title at the very least, but this should be long resolved I think. Full (well, almost... ) path customization and file name pattern to your heart's content are definitely a thing today in YTDL-M. :)
2. We have very fine progress indication now. Two digits after the period and it's really reliable. Even recently fixed for subdir users! (#500 )
3. Not quite sure how to interpret your distinction here. If you're still interested in this issue, don't hesitate to elaborate. Otherwise, I guess we can consider this solved if your list is two thirds actually solved and one third not applicable anymore. You tell us. :) 👍

**Comment by ibrahimk157** [comment]
> Going through old issues, cleaning them up, getting back to folks, etc... 🎶🎵 :)
> 
> 1. I don't quite remember if I've ever seen YTDL-M download to a filename that isn't the title at the very least, but this should be long resolved I think. Full (well, almost... ) path customization and file name pattern to your heart's content are definitely a thing today in YTDL-M. :)
> 2. We have very fine progress indication now. Two digits after the period and it's really reliable. Even recently fixed for subdir users! ([Recognize Parent folder in Default file Output #500](https://github.com/Tzahi12345/YoutubeDL-Material/issues/500) )
> 3. Not quite sure how to interpret your distinction here. If you're still interested in this issue, don't hesitate to elaborate. Otherwise, I guess we can consider this solved if your list is two thirds actually solved and one third not applicable anymore. You tell us. :) 👍

Let me provide an update on all three:

1) This issue doesn’t occur anymore and it appears to have been fixed. 

2) I’m guessing that’s under the nightly builds? Since I’m currently running the latest stable build (v4.2). If so, that’s lovely to hear!

3) As you can already tell, I suck as explaining stuff clearly haha. But here’s my re-attempt: Let’s say I’m downloading a massive 3 hour long video. With the current system where we have to wait for the server to first download it to itself, then providing the user with a download link, that could take ages. In situations like these, I was thinking of having an option to provide the user with the direct youtube link to the video such that the user directly downloads the video instead of having to wait for the server to download it first. Again, sorry for my horrible explanation!

**Comment by GlassedSilver** [comment]
Hmm, considering that your downloads will just cancel in your browser if yt-dlp (or whichever fork you may use, although yt-dlp is highly recommended) runs into problems like rate limiting (error 429, URLOpen Errors, …) I’m not sure that’s a wise approach. At least thanks to YTDL-M’s new feature #420 (tracked in issue #411 ) you can observe the status of your downloads and act on errors! :)

I can see why you want that feature, basically you want a feature where we bypass downloading permanently to the server YTDL-M runs on, don’t want the entry added to your YTDL-M database and ytdl archive and just output whatever ytdl gets to a browser download. Correct me if I’m wrong.

I still think for error handling it’s important to download to server first so we can pick up on downloads if they canceled for whatever reason, because straight to client (browser) means you cannot continue cancelled downloads, they would have to start over.

Maybe a temporary download to server which then pings your browser for readiness could be a thing? 


Sidenote: Browser notifications are something that may be worth implementing anyhow for various events. (e.g. a channel that seems on hiatus starts uploading again after a long while?)

**Comment by ibrahimk157** [comment]
> Hmm, considering that your downloads will just cancel in your browser if yt-dlp (or whichever fork you may use, although yt-dlp is highly recommended) runs into problems like rate limiting (error 429, URLOpen Errors, …) I’m not sure that’s a wise approach. At least thanks to YTDL-M’s new feature #420 (tracked in issue #411 ) you can observe the status of your downloads and act on errors! :)
> 
> I can see why you want that feature, basically you want a feature where we bypass downloading permanently to the server YTDL-M runs on, don’t want the entry added to your YTDL-M database and ytdl archive and just output whatever ytdl gets to a browser download. Correct me if I’m wrong.
> 
> I still think for error handling it’s important to download to server first so we can pick up on downloads if they canceled for whatever reason, because straight to client (browser) means you cannot continue cancelled downloads, they would have to start over.
> 
> Maybe a temporary download to server which then pings your browser for readiness could be a thing?
> 
> Sidenote: Browser notifications are something that may be worth implementing anyhow for various events. (e.g. a channel that seems on hiatus starts uploading again after a long while?)

You do have a point there! And I like the idea of a temporary download to the server!

**Comment by GlassedSilver** [comment]
Tracked in #578 now
