### ISSUE TITLE
Problem with multiuser

### ISSUE THREAD

**Issue by honza1978** [Tzahi12345/YoutubeDL-Material#98]
I have allowed multiuser and also user registration (and also changed name of the page from "Youtube Downloader"  to something else)….then when I log off and reload the page or use "home" button in the left menu I get back the different #/home page (with original name Youtube Downloader header) and in this home page is even possible to start download from youtube links.
There is no way how to get the login page back unless I add #/login behind my domain name. When so, I can see only login section, registration section is missing.

Thank you.

**Comment by Tzahi12345** [comment]
Ok, I think there's a couple bugs in here that I need to address.

1. The only thing that should appear in the hamburger menu when logged out is "Login", having "Home" show up is unintuitive because it won't work everywhere.
2. I believe registration/top title are both broken for the same reason. Basically, if you're not logged in, you won't receive the server configuration, and therefore don't know if user registration is allowed or what the top bar title is.

The 2nd one is quite a serious bug. I'll see if I can get a fix out today, if not I'll make sure to put one out this weekend.

Also, note that even though you can see the Home page when you're not logged in, downloading (and all other functionality) will fail.

Thanks for the bug report! Not sure if I would have found it myself, it's a good catch.

**Comment by Tzahi12345** [comment]
Good news, the bug has been fixed! Registration should work as intended, and the options to go "home" are now missing for users that are not logged in. Also, the top title should also appear normally when not logged in as well. Here's the [relevant commit.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/cec0ed78ecfca628e84059462ade664509a11eb6)

Let me know if you face any other issues, thanks for the report! Much appreciated.
